### ISSUE TITLE
v2/package endpoint does not match specification

### ISSUE THREAD

**Issue by tomzo** [loic-sharma/BaGet#106]
### Do you want to request a *feature* or report a *bug*?

Bug / question

### What did you do?

I have started porting e2e tests from nuget.org. One of first things that fails is upload into `v2/package` endpoint. I am a bit confused since in 3.0 specification it says that upload should be a [multipart form](https://docs.microsoft.com/en-us/nuget/api/package-publish-resource#multipart-form-data). But actual nuget.org tests just stream the [nupkg directly to endpoint](https://github.com/ai-traders/NuGet.Services.EndToEnd/blob/master/src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs#L126).
@loic-sharma what do think, should BaGet accept `multipart/form-data` or `application/octet-stream` at `v2/package` ?

Currently when client from e2e tests is uploading, on server side we get null package and 400:
```
public async Task Upload(IFormFile package)
        {
            if (package == null)
            {
                HttpContext.Response.StatusCode = 400;
                return;
            }
```

**Comment by loic-sharma** [comment]
Interesting... this seems like a bug on nuget.org. My gut feeling is that we should stick to the specification and patch the tests here. What do you think?

**Comment by tomzo** [comment]
> Or maybe we could fallback to reading the request's body if package is null? What do you think?

Will do that. Same as nuget.org.

**Comment by loic-sharma** [comment]
I opened an issue on NuGet's documentation: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1076

**Comment by BlythMeister** [comment]
I just started testing as found this exact issue when using paket to push to the V2 endpoint.

**Comment by tomzo** [comment]
I got this working with paket now. I haven't opened a PR yet, but if you like to cherry-pick https://github.com/ai-traders/BaGet/commit/1826580843e1d0ba585627affed6dfc72e15a7d3

That's not the only thing for paket to work though. You'll need #104 too

**Comment by BlythMeister** [comment]
I'm ok to wait for now 😀
I'm just testing out tooling, but so far I like baget. 👍

**Comment by loic-sharma** [comment]
This should be fixed by https://github.com/loic-sharma/BaGet/commit/1f1ec07826ec26c83d02dbca2ae834db23728fd1 now.

**Comment by loic-sharma** [comment]
Closing this issue as it should now be fixed. Feel free to open a new issue if you run into any other problems!
