### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by rong0312** [loic-sharma/BaGet#109]
### Do you want to request a *feature* or report a *bug*?

**Bug**

###

My company uses BaGet over  a month (docker based). 
Yesterday we noticed that dependencies are not listed, not in VS and neither in the web UI
(pics attached), this is true for ALL packages;

This is the current state of "Select2.js" from our local BaGet-

![screen shot 2018-10-22 at 8 46 12](https://user-images.githubusercontent.com/33253167/47279077-2299f480-d5d7-11e8-9a91-299547d60eea.png)

### What did you expect to see?

This is current state of the same package but from the global nuget.org-

![screen shot 2018-10-22 at 8 41 10](https://user-images.githubusercontent.com/33253167/47279082-35142e00-d5d7-11e8-916e-2544aa654ae7.png)

As you can see, from the global Nuget there are dependencies view and access,
Did anyone else encounter this issue? 
Do i have to append / enable some features in the code? 

Thank a lot

**Comment by rong0312** [comment]
Please notice my PR regards this issue. 
We found solution that works in our company.

**Comment by rong0312** [comment]
Please notice my PR regards this issue.
We found a solution that works in our company.

**Comment by loic-sharma** [comment]
This was fixed by @rong0312 by https://github.com/loic-sharma/BaGet/pull/110
