### ISSUE TITLE
nuget delete then show conflict 

### ISSUE THREAD

**Issue by alberk8** [loic-sharma/BaGet#111]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have a nuget packaged pushed to BaGet then  issue the nuget delete command then push back the same package.

dotnet nuget delete -s http://192.168.1.1:5000/v3/index.json MyPlugin.Net  1.0.9
### This went well

dotnet nuget push -s http://192.168.1.1:5000/v3/index.json MyPlugin.Net 1.0.9
### What did you expect to see?
Push successful

### What did you see instead?
info : Pushing MyPlugin.Net.1.0.9.nupkg to 'http://192.168.1.1:5000/v2/package'...
info :   PUT http://192.168.1.1:5000/v2/package/
info :   Conflict http://192.168.1.1:5000/v2/package/ 59ms
error: Response status code does not indicate success: 409 (Conflict).

### Output of `git rev-parse HEAD`: (_What version of BaGet are you using?_)

```
(paste your output here)
6a4bbdc5139c81d018b3a36ad4cda38a2db53298
```

### What is your environment & configuration (arguments, platform, ...)?
Linux Ubuntu 16.04

### If applicable, please paste the log output in DEBUG level

```
(paste your output here)
```

**Comment by rong0312** [comment]
I have the same issue!
following.

**Comment by alberk8** [comment]
Looking at the code the Delete function just update  the "delete flag" in the DB. Also delete the record still will not work as the nuget  package in the Package directory also needs deleting.  Please can someone look into this if this is a Feature or a Big Bad Bug.  :)

**Comment by BlythMeister** [comment]
I think the nuget behaviour (and current implementation) is correct.
A delete is an unlisted.
You should never republish the exact same version...it's against what versioning is all about.
If something has changed, the version should have changed.

**Comment by BlythMeister** [comment]
Potentially, a "show unlisted" option in the UI might be useful to prevent the confusion. I've long thought about that for nuget.org.
Essentially, you can use an unlisted package...but it was unlisted for a reason 😉

**Comment by loic-sharma** [comment]
@BlythMeister A package owner can already see their own unlisted packages on nuget.org, which should covers most needs. I'm not sure if this has been announced yet, but we are planning improvements to the unlisted feature on nuget.org to enable more advanced scenarios (bulk releases of packages, package deprecation, security issues, etc).

**Comment by rong0312** [comment]
An actual deletion or just an unlisted package doesn't matter to me personally, as long as we won't receive 409 error code :)

**Comment by BlythMeister** [comment]
I guess my query is why are you pushing the same version again?
As a consumer of your feed, if you remove and republish, the underlying package is new, but I have no way to know.

**Comment by alberk8** [comment]
> Good question! This is actually intended. The [delete operation on nuget.org](https://docs.microsoft.com/en-us/nuget/policies/deleting-packages) doesn't actually delete the package, instead, it "unlists" the package. In other words, the delete operation simply makes a package undiscoverable. You can still download the package if you know its id/version. This prevents the ["left pad" problem](https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm).
> 
> I can add a configuration option that makes the delete operation actually delete the package. Does that sound good? I'll add some documentation too as this can be confusing.

I like the idea of having a config setting where Delete is an actual delete action.  Thank you.

**Comment by alberk8** [comment]
> I guess my query is why are you pushing the same version again?
> As a consumer of your feed, if you remove and republish, the underlying package is new, but I have no way to know.

The Delete action should be a actual delete as most people understands it.  Otherwise call it unlist.

**Comment by BlythMeister** [comment]
Unlist isn't a http verb though 😉

**Comment by BlythMeister** [comment]
Maybe rather than a config flag, a delete and unlist should be included.

**Comment by loic-sharma** [comment]
> Maybe rather than a config flag, a delete and unlist should be included.

As in, there should be separate APIs for deleting/unlisting? We could do this too, but I'm not sure how valuable it would be considering the NuGet client only has a single "delete" command. I'll go with the config option for now as that's what NuGet.Server does, and no one has asked for more :)

**Comment by loic-sharma** [comment]
@alberk8 I've added a config, [`PackageDeletionsBehavior`](https://loic-sharma.github.io/BaGet/configuration/#enabling-package-hard-deletions). Please test it out and let me know what you think 😄

**Comment by loic-sharma** [comment]
Closing this as the deletion config has been added. Feel free to open a new issue if you have any additional suggestions.
