### ISSUE TITLE
Mirroring fails unless Nuget.Common is added explicitly

### ISSUE THREAD

**Issue by memsom** [loic-sharma/BaGet#112]
I was trying to set up Nuget.Org mirroring and the MirroringService was throwing an exception every time a request was made that "Nuget.Common 4.7.0.x" was missing. 

I found this to be an issue when trying to set up the server from scratch. I built the source in Visual Studio and ran once, then disabled the Nuget.Org feed in VS2017 and enabled the read through caching. The app would then throw an exception on line 71 of MirroringService.cs (this is from memory). Problem is that I now have that package cached locally and so can't recreate the issue.

My fix was pretty simple; if I add the Nuget.Common.4.7.0.nupkg to both the Baget and BaGet.Core projects, the pass through cashing now works first time. It's such a small change, but it seems to make the server happy.

I have a branch with the fix in it (and also the appsetting.json was changed to meet our needs, so I won't do a pull request from that branch...) It's probably worth adding that in though, as it wasn't obvious as to what was failing until I stepped through the code.

https://github.com/memsom/BaGet/tree/Fixes/make_readthrough_work

**Comment by loic-sharma** [comment]
Hey, I'd like to understand the issue a little bit better before I add a reference to `NuGet.Common`. Would you be able to give me the full exception? You should be able to clear your local NuGet fallback by deleting the folder at `C:\Users\<username>\.nuget\packages\<id>\<version>\` and launching a new instance of BaGet. Thanks!

**Comment by loic-sharma** [comment]
I haven't been able to reproduce this. If anyone else runs into this, please let me know and we can reopen this issue.
