### ISSUE TITLE
Package not found in primary source error

### ISSUE THREAD

**Issue by toptensoftware** [loic-sharma/BaGet#118]
I've noticed that when I upgrade a package from a BaGet source from within Visual Studio 2017, it works the first time, but subsequent attempts to update give the error "Package not found in primary source".  

See error window in screen shot:

![image](https://user-images.githubusercontent.com/179862/48103186-2f2e7600-e282-11e8-9290-022421d02c43.png)

Restarting Visual Studio solves the problem, seems like a caching issue. The server in question is running on ubuntu behind a nginx reverse proxy.  nginx script is as follows:

~~~
server {
    server_name REDACTED;
    access_log REDACTED;
    listen 80;
    auth_basic "REDACTED";
    auth_basic_user_file REDACTED;
    location / {
        proxy_pass http://127.0.0.1:50561;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 20M;
    }
}
~~~

**Comment by loic-sharma** [comment]
Could you provide BaGet's logs while reproducing this issue? I would recommend raising the `LogLevel`s to `Debug`.

**Comment by loic-sharma** [comment]
I haven't been able to reproduce this. We can reopen this if someone runs into this issue again

**Comment by patterson-philip** [comment]
I'm also receiving an issue similar to this. I am running baget via docker container:

https://hub.docker.com/r/anuraj/baget/

When I do a nuget push to the same repository twice the second one errors when trying to resolve. The steps that reproduce for me are:

1. Push a package to the baget server
![image](https://user-images.githubusercontent.com/1644123/54846026-4d38c800-4cb1-11e9-8149-696ab81d8387.png)

2. Make changes to the nuget package and deploy
# dotnet nuget push -s http://localhost:8000/v3/index.json ExceptionEngine.1.0.0-Beta03.nupkg -k NUGET-SERVER-API-KEY
info : Pushing ExceptionEngine.1.0.0-Beta03.nupkg to 'http://localhost:8000/api/v2/package'...
info :   PUT http://localhost:8000/api/v2/package/
info :   Created http://localhost:8000/api/v2/package/ 726ms
info : Your package was pushed.
![image](https://user-images.githubusercontent.com/1644123/54846135-8b35ec00-4cb1-11e9-97e2-6e9e80863947.png)

3. Try to update nuget package in VS but receive the following error:
Package 'ExceptionEngine 1.0.0-beta04' is not found in the following primary source(s): 'http://localhost:8000/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly.
![image](https://user-images.githubusercontent.com/1644123/54846254-d18b4b00-4cb1-11e9-8cbf-0a628b994ab3.png)

In my case the only thing that allows me to push packages to the server after this starts occuring is to remove the container and recreate it from scratch. The error seems to only occur on Pre-Release version of packages but I can't be 100% sure of this. 

I would update the log level for Baget but I'm unsure how to get to the log file running in the docker container.

**Comment by WernerMairl** [comment]
Hi

may be you are using the wrong container (anuraij/baget) (see #212, the user there has the same problem).

about logging in Linux/docker:

1. increase the the tracing level, some sample/instructions here: https://github.com/loic-sharma/BaGet/issues/235#issuecomment-473782205

2. how to get the log/trace info
the complicated way: if you define a file based logger then you can define a docker volume on the host and read the file from the volume (do you need host access).

the easier way -  if you have a local docker client up and running
use console logging (like in my sample) and grab the console....

i hope that helps!

**Comment by loic-sharma** [comment]
Let us know if using your issue still happens after you use the official image @patterson-philip

**Comment by patterson-philip** [comment]
Using the correct docker container I was able to recreate and pull from the nuget repository. It would be nice if the official image on docker hub could have a verified check-mark or something similar, but that's an issue for them and not you guys. Everything works great now so far. If I find any issues I'll raise those as needed, but as of now it works like a dream.

Thanks a lot everyone!

**Comment by jswolf19** [comment]
>     2\. how to get the log/trace info
>         the complicated way: if you define a file based logger then you can define a docker volume on the host and read the file from the volume (do you need host access).

@WernerMairl Sorry to post on a closed issue for this, but are there any docs you can point to for how to define a file-based logger for baget to use? Is this something that can be done just by editing config files? My google-fu seems to be failing me...
