### ISSUE TITLE
After yarn install/develop I got an error

### ISSUE THREAD

**Issue by ridomin** [loic-sharma/BaGet#123]
I installed dotnet, node.js, and yarn (all latest versions).

after running yarn install, and yarn develop I got:

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.13.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\code\BaGet\src\BaGet.UI> yarn develop
yarn run v1.12.3
$ parcel ./index.html
'parcel' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by loic-sharma** [comment]
Good catch! It looks like a dependency is broken on Node.js 10, but the build breaks if I blindly rev all the dependencies forward. I'll have to dig deeper into this.

For now, you can get around this by running Node.js 9.

**Comment by loic-sharma** [comment]
This issue should be fixed by https://github.com/loic-sharma/BaGet/pull/125. Could you verify @ridomin?

**Comment by loic-sharma** [comment]
Verified that BaGet can be build with Node.js 10 after https://github.com/loic-sharma/BaGet/pull/125. Feel free to open a new issue if you run into any other issues :)

**Comment by rido-min** [comment]
fixed. Thanks !!
