### ISSUE TITLE
How do I connect this service remotely?

### ISSUE THREAD

**Issue by humblesticker** [loic-sharma/BaGet#126]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Documentation/How-to for remotely installing and accessing this service

**Comment by loic-sharma** [comment]
Did you try [the Getting Started](https://github.com/loic-sharma/BaGet/#getting-started) guide? Did you have issues following that?

**Comment by loic-sharma** [comment]
Closing this off due to inactivity. Please let me know if you have any additional questions
