### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by Moser-ss** [loic-sharma/BaGet#128]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Hey, I am trying to run the docker build at it keeps failing. But I just fix in my environment and I would like to push my branch with the fix to the repo but I cannot push 

```(shell)
 git push --set-upstream origin Fix-Docker-Build
ERROR: Permission to loic-sharma/BaGet.git denied to Moser-ss.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Output of `git rev-parse HEAD`: (_What version of BaGet are you using?_)

```
(paste your output here)
```

### If applicable, please paste the log output in DEBUG level

```
(paste your output here)
```

**Comment by loic-sharma** [comment]
It looks like you’re trying to push your branch to this repository directly. You should instead create a fork of my repository, create a new branch on your fork, and push your changes to the fork. GitHub will then let you to open a pull request here.

**Comment by loic-sharma** [comment]
Thank you for reporting! This should be fixed by: https://github.com/loic-sharma/BaGet/pull/132
