### ISSUE TITLE
Make BaGet a symbol server

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#130]
BaGet should:

1. Have an endpoint to ingest [symbol packages (.snupkg)](https://docs.microsoft.com/en-Us/nuget/create-packages/symbol-packages-snupkg)
2. It should be able to extract portable PDBs embedded into a nupkg
3. It should be able to respond to symbol server requests. See [this API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/symbol/?view=azure-devops-rest-4.1)

See https://github.com/dotnet/symstore/blob/master/docs/specs/Simple_Symbol_Query_Protocol.md
See https://github.com/dotnet/symstore/blob/master/docs/specs/SSQP_Key_Conventions.md
See https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md
See https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md

See https://github.com/dotnet/symstore/tree/master/src/NugetSymbolServer

/cc @karann-msft

**Comment by SwooshyCueb** [comment]
Duplicate of #11?

**Comment by loic-sharma** [comment]
Oops, good catch! This issue includes snupkg ingestion which was just released yesterday in Visual Studio 15.9, so I’ll close the other issue.

**Comment by loic-sharma** [comment]
Finished by https://github.com/loic-sharma/BaGet/pull/134
