### ISSUE TITLE
AWS support (S3)

### ISSUE THREAD

**Issue by LordMike** [loic-sharma/BaGet#136]
Hi,

What is needed for S3 support? I can see the Azure project has a few things in it:

* Blob service
* Search service using Azure Search

This directly translates to:

* S3 storage (can we do it so that end users download from S3 directly?)
* AWS CloudSearch (never used it)
  * Is search necessary? Wouldn't a query in the EF DB be enough?
  * I imagine most queries want to prefix match on the Package Id anyways

Would implementing an S3 client be enough?

**Comment by loic-sharma** [comment]
BaGet has three core pieces:

* Package metadata - this needs a database of some sort
* Content storage - BaGet stores packages and will soon store symbols
* Search - this can be database backed, or use some external search provider

S3 is definitely needed for storage. For package metadata, we may need to port BaGet to PostgreSQL to run on Aurora.

Search on BaGet is still infancy. I need to flesh out Azure search to get a better understanding of what works and what doesn't. Hopefully, these learnings should carry over to AWS.

**Comment by LordMike** [comment]
But would it be possible to run BaGet on S3, keep the Sqlite and keep some local search implementation (lucene?)

**Comment by LordMike** [comment]
I'd very much like (possibly make) the S3 support. :P
