### ISSUE TITLE
UI: Empty license info, link leads to front page

### ISSUE THREAD

**Issue by LordMike** [loic-sharma/BaGet#138]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

* Upload package with no License

### What did you expect to see?

* No license link

### What did you see instead?

* BaGet UI provides link back to `/`

![image](https://user-images.githubusercontent.com/1027111/49259189-9c27cc80-f438-11e8-9d1a-95f3527c44ff.png)

### Output of `git rev-parse HEAD`: (_What version of BaGet are you using?_)

988af77e1d997560527685a3442ac3d236eccb7f

### What is your environment & configuration (arguments, platform, ...)?

N/A

### If applicable, please paste the log output in DEBUG level

N/A

**Comment by loic-sharma** [comment]
Thanks for reporting! This should be fixed by #143
