### ISSUE TITLE
UI: Add setup page describing how to add the repository to nuget config(s)

### ISSUE THREAD

**Issue by LordMike** [loic-sharma/BaGet#139]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

* A link or page describing how to add the Package Repository to a `Nuget.config`
  * Either the users config file
  * Or a project-specific `Nuget.config` file.
* The page should include the actual url, and in case of Private Feeds (#36), a key (if possible) in the feed url

I imagine that next to the BaGet title, an "info" or "setup" link could be added.

**Comment by loic-sharma** [comment]
So far I've been putting this type of information in the documentation. Do you think the documentation is a good place for this? I could add a link to the documentation directly from BaGet's UI too, if that makes discovery easier.

**Comment by LordMike** [comment]
You should absolutely add a link to documentation, from the running instances. 

But. I'd still add a custom page that includes _my_ url. You could show how to:

* Add _my_ url to feeds ("Add \<url\> to the Nuget package repositories in VS")
* Push a package to _my_ url ("nuget push SamplePackage.1.0.0.nupkg \<your access token\> -Source \<my url\>")
* Add symbols url to VS with _my_ url

This would make the adoption easier for new developers who can just be pointed at BaGet and get up to date information on what to do. They don't have to do any url replacements to replace "localhost" in the documentation with some custom domain. It'd make it self-explaining :).

**Comment by LordMike** [comment]
Looks great. Awesome with this new UI. I take it Routing made its way in now, so we can start using paths - ie. show different versions of packages :D ?

Notes:

* The push command includes newtonsoft in 2 out of 3 cases, Paket is the odd one out
  * I'd use `package.nupkg` instead of newtonsoft. (less characters to remove after pasting, while still keeping it concise)
* The link to docs should be `target="_blank"`

**Comment by loic-sharma** [comment]
Great feedback! I’ll fix those up next week. 

Yup, routing has been added! I didn’t add in version specific package browsing as the UI overhaul was getting pretty big. It shouldn’t be too hard :)

**Comment by loic-sharma** [comment]
Okay, I went ahead and addressed all your feedback:

* [X] Upload examples now use `package.nupkg`
* [X] The paket push example now has a package
* [X] Link to docs opens in a new tab
* [X] You can now browse different versions of a package

Feel free to open a new issue if you have any additional suggestions! :)
