### ISSUE TITLE
IOptionsSnapshot<T> cannot be used from Singletons

### ISSUE THREAD

**Issue by LordMike** [loic-sharma/BaGet#156]
`IOptionsSnapshot<T>` [cannot be used from singletons](https://github.com/aspnet/AspNetCore/issues/2380).

Issue is present in the ApiKey authentication service. I workarounded it by registering the auth service as scoped.

**Comment by loic-sharma** [comment]
Ah good catch. Let's make it transient since it doesn't actually need a scope.

Fix here: https://github.com/loic-sharma/BaGet/blob/1079782ff2d9e18b8ac573ca9b4f8fef48f15e7a/src/BaGet/Extensions/ServiceCollectionExtensions.cs#L260

**Comment by LordMike** [comment]
Don't you want to use an OptionsMonitor instead?. It gives you updates, can bed used in Singletons and so on..

**Comment by LordMike** [comment]
Well. I'd keep all services at the highest scope possible, so Singleton preferably, then Scoped and finally Transient. This is to create as few instances of a service as possible. So if a service has nothing with a specific request to do, and has no unmanaged resources (ie. not a DB), I'd make it singleton.

And for Singletons, IOptionsMonitor is a good fit. Its Value should always be the "current" value, so you could just use it as is. Alternatively, there is an event that you can listen to that fires when the Value changes.

I also assume, for compatibility, that when the Value changes, its an entirely new object. So it should be possible to, if you need to read two properties off of a Configuration object, to copy the reference of the Value object, and then use that. It shouldn't change once it's been copied out.

**Comment by loic-sharma** [comment]
> Well. I'd keep all services at the highest scope possible, so Singleton preferably, then Scoped and finally Transient. This is to create as few instances of a service as possible. So if a service has nothing with a specific request to do, and has no unmanaged resources (ie. not a DB), I'd make it singleton.

The NuGet team does the exact opposite. We always use Transient, unless something has to be Scoped/Transient. This reduces the likelihood of errors at the cost of a minor performance hit. This seems to be a worthwhile trade-off: we've had issues like singletons depending on scoped objects before, but we've never had a performance issues due to overzealous dependency injection configurations.

Thanks for the info on `IOptionsMonitor`. The documentation on that is quite sparse 😢

**Comment by LordMike** [comment]
I find that odd thinking. But then, it's up to a measurement to find the impact.

For now, this is a bug that prevents uploading of packages. :)
