### ISSUE TITLE
UI: Show package dependencies and dependents

### ISSUE THREAD

**Issue by LordMike** [loic-sharma/BaGet#157]
Add a UI feature to show package dependencies (what _this_ package depends on), and dependents (which _other_ packages depends on _this_ package) -- within the BaGet system ofc.

Links to other packages may have to be "closest possible".

* PackageA depends on PackageB.1.0.0
* PackageB only exists in version 1.2.0
* PackageA's page should show a dependency of `PackageB >=1.0.0`, but link to `PackageB 1.2.0` (maybe have a warning sign)

**Comment by LordMike** [comment]
This has two steps IMO:

* Visualize dependencies as stored in the DB (simple listing of supported frameworks and requirements)
* Link to packages from the same feed, that match the criteria in the dependency
  * Initially, linking to *a package* is enough
  * Ideally, linking to the *actual package* that would be restored

**Comment by loic-sharma** [comment]
I like this idea. As a package owner, I'd love to see who depends on my packages. As a package  consumer, I'd love to see what I'd pull in by depending on a new package. All around, there's lots of utility here.

>   * Ideally, linking to the _actual package_ that would be restored

I don't think this is possible due to version ranges.

**Comment by LordMike** [comment]
NuGet does it... :)
