### ISSUE TITLE
UI: npm test fails with an error

### ISSUE THREAD

**Issue by ku3mich** [loic-sharma/BaGet#165]
`npm test `

fails with an error:
`
...BaGet.UI\node_modules\office-ui-fabric-react\lib\Icon.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './components/Icon/index';
                                                                                         ^^^^^^

SyntaxError: Unexpected token export

  1 | import { HtmlRenderer, Parser } from 'commonmark';
> 2 | import { Icon } from 'office-ui-fabric-react/lib/Icon';
    | ^
  3 | import * as React from 'react';
  4 | import timeago from 'timeago.js';
  5 | import LicenseInfo from './LicenseInfo';

  at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
  at Object.<anonymous> (src/DisplayPackage.tsx:2:1)
`

similar to this https://github.com/facebook/jest/issues/2550

I have updated npms to the latest but it does not resolve the issue.

**Comment by sipmann** [comment]
I'd like to work on this if is available.

**Comment by loic-sharma** [comment]
Go for it! I'm not familiar with testing frontend applications, so I look forward to learning more about it :)

**Comment by loic-sharma** [comment]
By the way, in case you're interested @sipmann I have lots of wacky ideas for BaGet's frontend that I haven't captured in issues:

* Create a npm module to interact with the NuGet protocol, similar to BaGet's [`BaGet.Protocol`](https://github.com/loic-sharma/BaGet/tree/master/src/BaGet.Protocol) library (see these [docs](https://loic-sharma.github.io/BaGet/tools/sdk/)).
* Create a VS Code extension that provides a UI to interact with a .NET project's NuGet packages, similar to Visual Studio's Package Manager UI. This would leverage BaGet's frontend as much as possible.

Please let me know if you're interested in those ideas! Also happy to hear any ideas you may have too :)

**Comment by sipmann** [comment]
awesome, I'll make a branch and start working on this new features and fill an issue next week to keep track. 
I'll fix the tests and code a few ones. React testing isn't my strongest front-end test but I'm sure we can improve what we have here ;)

**Comment by sipmann** [comment]
Question: We'll follow what we have today with the "app.test" and keep the test files side bi side with the testing component? 
Or move to a separated folder to keep things clean?

**Comment by loic-sharma** [comment]
Good question! Do you have a preference between the two approaches? I'm fine with both, but I'd prefer whatever is standard in the React community.

**Comment by sipmann** [comment]
I'll keep the patter that Create React Script use. But I'm stuck with mocking the fetch request. I saw that you have a `__BAGET_PLACEHOLDER_API_URL__` on the `config.tsx`. What's the purpose of this? I'm asking because I have an issue while runing tests. The test require a full URL to mock, not just `/v3/search?...`.

**Comment by loic-sharma** [comment]
> I'll keep the patter that Create React Script use.

Sounds good to me

> But I'm stuck with mocking the fetch request. I saw that you have a `__BAGET_PLACEHOLDER_API_URL__` on the `config.tsx`. What's the purpose of this?

Good question! This can be used by two things:

1. Normally, the BaGet backend serves the BaGet react app, and the react app uses relative URLs. These URLs is broken if you add a prefix to BaGet's URLs (example: `/upload` would become `/my-prefix/upload`). We're working on a fix to this problem [here](https://github.com/loic-sharma/BaGet/pull/511/files#diff-0191f7d54f67c93e089e655a4310ae01R67), it works by replacing that `__BAGET_PLACEHOLDER_API_URL__` value as we serve the BaGet react app.
1. This lets you run the BaGet react app separately from the BaGet backend. Say you run the backend at URL `https://my-baget-api`, you can create a deployment step where you replace `__BAGET_PLACEHOLDER_API_URL__` with `https://my-get-api`. This is a hidden feature that I should document :)

> I'm asking because I have an issue while runing tests. The test require a full URL to mock, not just `/v3/search?....`

Hm. Could you use custom environment variables (see [this](https://create-react-app.dev/docs/adding-custom-environment-variables/)) to override the API URL?
