### ISSUE TITLE
IoC registration issue 

### ISSUE THREAD

**Issue by ku3mich** [loic-sharma/BaGet#166]
after refactoring commit d33a1768 contains registration IAuthenticationService as Singleton which is incorrect because IOptionsSnapshot is not avaiable see
https://github.com/aspnet/AspNetCore/issues/2380

System.InvalidOperationException: Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[BaGet.Core.Configuration.BaGetOptions]' from singleton 'BaGet.Core.Services.IAuthenticationService'.

**Comment by loic-sharma** [comment]
Are you on the latest version of BaGet? `IAuthenticationService` is registered as a transient service as of https://github.com/loic-sharma/BaGet/pull/159

**Comment by ku3mich** [comment]
it was, but did not see your changes, anyway changed to scoped instead of transient
