### ISSUE TITLE
migrate to NHibirnate Core

### ISSUE THREAD

**Issue by ku3mich** [loic-sharma/BaGet#168]
just proposal - I can this, need only an agree

**Comment by ku3mich** [comment]
#167 related

**Comment by ku3mich** [comment]
The idea to migrate NH is based on the fact I discover that EF Core does not support group by(even EF 2.2 #167 and in further plans, you can investigate this starting from this thread for example https://stackoverflow.com/questions/48082277/entityframework-core-group-by-gives-me-an-order-by) 
Also while the investigation I've found that EF Core has also troubles with joins, count, order by. I was very surprised by these facts because EF 6 does it perfectly. From other side I see a lot of new features such as Symbol Server or  and taking into consideration fact that primary NuGet server is used to search/retrieve the results of NuGet by various criteria I do not think that EF Core is right ORM(at least at future several years). NH much more flexible and powerful(quality of sql primary) than EF and to avoid further troubles and while we have only two tables in DB I think we need to migrate to NH.

**Comment by loic-sharma** [comment]
I would like to avoid changing our database provider until we absolutely need to. If anything, I would rather move to EF6 than NHibernate, and EF6 will be supported on .NET Core 3, which is currently in preview. Does that seem reasonable? I'll close off this issue for now, but feel free to add any comments.

**Comment by ku3mich** [comment]
I would like to do not agree that moving back to EF6 is reasonable ( EF6 in compare NHibernate is much more weaker ORM.
From other side NH supports such features as shards, search, caching which may help in cases when 'Pacakges' table contains a thousands of packages.
So migrating now to NH will resolve a lot of future issues.

also for Azure lovers(maybe interesting fact):
https://ayende.com/blog/4178/sql-azure-sharding-and-nhibernate-a-call-for-volunteers

**Comment by loic-sharma** [comment]
NuGet.org uses entity framework and scales to 2 million records without any sharding. I’ve also indexed all of NuGet.org using BaGet on a single database. I don’t think there’s a need to replace the current solution at this time. I’ll read up more about the caching and searching though, that could be useful!
