### ISSUE TITLE
DB Migration needed

### ISSUE THREAD

**Issue by LordMike** [loic-sharma/BaGet#181]
While creating db migrations, I noticed that `PackageDependency` has changed a property since the last migration was made. Can you, @loic-sharma, create a migration in `master` to make sure the EF model matches the C# model?

**Comment by loic-sharma** [comment]
Good catch. I’ll fix this next week when I’m back from the holidays

**Comment by loic-sharma** [comment]
This should be fixed now, thanks for reporting this :)
