### ISSUE TITLE
Add BaGet to awesome-dotnet

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#184]
Add BaGet to this section: https://github.com/quozd/awesome-dotnet#package-management

**Comment by jsreynolds** [comment]
@loic-sharma added tonight with pull request. 

https://github.com/quozd/awesome-dotnet/pull/755

**Comment by jsreynolds** [comment]
Awesome-dotnet accepted the pull and it's live.

**Comment by loic-sharma** [comment]
Thanks! :)

**Comment by loic-sharma** [comment]
Note to self, also add: https://github.com/thangchung/awesome-dotnet-core
