### ISSUE TITLE
No update message? Did you stop updating?

### ISSUE THREAD

**Issue by chenzuo** [loic-sharma/BaGet#193]
Updated 23 days ago, until now

**Comment by chenzuo** [comment]
no news?

**Comment by BlythMeister** [comment]
Just because this project hasn't had a change in just under a month does not mean it's dead.  Come back when a project has no updates for over 3 years...

**Comment by loic-sharma** [comment]
Hi, I’ve been abroad in Italy. I’ll be back next week :)
