### ISSUE TITLE
Official DockerHub image

### ISSUE THREAD

**Issue by BnMcG** [loic-sharma/BaGet#194]
It would be great if there was an official BaGet Docker image hosted on DockerHub, there are currently several 'unofficial' copies using various out-of-date versions.

I think it would be quite easy for the CI platform to push the built Docker image to DockerHub once any tests have passed, as the image itself is already built as part of the pipeline.

My main motivation for requesting this is to use an 'official' image with the Helm chart that I'm putting together for BaGet so that I can run BaGet on Kubernetes easily. I'll link the Helm PR here once I'm done.

**Comment by BnMcG** [comment]
https://github.com/helm/charts/pull/10835

PR for a Helm chart is here.

**Comment by loic-sharma** [comment]
Good idea! I'll start working on this :)

**Comment by loic-sharma** [comment]
You can find the official Docker image here: https://cloud.docker.com/u/loicsharma/repository/docker/loicsharma/baget

**Comment by HassanHashemi** [comment]
@BnMcG Any news on the helm chart? the PR seems to be closed.
