### ISSUE TITLE
Are symbol files corrupt?

### ISSUE THREAD

**Issue by loicmorvan-ansys** [loic-sharma/BaGet#195]
### Describe the bug
Symbol files downloaded from BaGet as symbol server cannot be opened by a debugger.

### To Reproduce
1. Using version 0.1.32-prerelease of BaGet
2. Run BaGet
  `dotnet BaGet.dll`
3. Have a package `MyPackage.1.0.0.nupkg` with `MyPackage.dll` and its symbol package `MyPackage.1.0.0.snupkg` containing its *portable* PDB `MyPackage.pdb`.
4. Upload this NuGet package.  
    ``` powershell
    nuget push -Source http://localhost:5000/v3/index.json MyPackage.1.0.0.nupkg
    ```
    Output:
    ``` log
    Pushing MyPackage.1.0.0.nupkg to 'http://localhost:5000/api/v2/package'...
      PUT http://localhost:5000/api/v2/package/
      Created http://localhost:5000/api/v2/package/ 555ms
    Your package was pushed.
    Pushing MyPackage.1.0.0.snupkg to 'http://localhost:5000/api/v2/symbol'...
      PUT http://localhost:5000/api/v2/symbol/
      Created http://localhost:5000/api/v2/symbol/ 125ms
    Your package was pushed.
    ```
5. In Visual Studio, add the NuGet package `MyPackage.1.0.0` from the BaGet server to a csproj that generates an executable.
6. Configure `Tools → Options → Debugging → Symbols` to add symbol server `http://localhost:5000/api/download/symbols` with a symbols cache folder.
7. Launch the csproj with Visual Studio debugger attached. See that Visual Studio is not able to load the PDB for MyPackage.
9. Go to the symbol cache folder and open `MyPackage.pdb` (supposed to be downloaded from BaGet) with a text editor to see that its content seems to be an html page:
    ``` html
    <!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="description" content="BaGet"><meta name="author" content="Loic Sharma"><title>BaGet</title><link href="/static/css/main.f0058ac5.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="/static/js/main.c6ef3653.js"></script></body></html>
    ```

### Expected behavior
The content of the PDB file provided by BaGet should be the same as the content of the PDB from the symbol package uploaded.

**Comment by loic-sharma** [comment]
Thank you for reporting this. It seems that the symbol server feature has regressed somehow, I will investigate.

**Comment by loic-sharma** [comment]
This should be fixed now, could you verify @loicmorvan-ansys? I apologize for taking so long to fix this, please let me know if you run into any additional issues!
