### ISSUE TITLE
Feature Request: Enable package overwrites

### ISSUE THREAD

**Issue by bkraul** [loic-sharma/BaGet#196]
### Describe the solution you'd like
An option to replace packages with matching version number would be nice. Right now, even with ```HardDelete``` set, I still get ```409 - conflict``` when replacing the package. I read about the whole left-pad thing, and I understand it, but our organization's needs are different. It would help if the UI allowed for proper package management, but I understand it is in early stages, and it is looking GREAT!

We are currently using [phpNuget](https://github.com/kendarorg/PhpNuget), which supports deletion and replacement, but we are seeing very slow activity in the development and are looking for other options.

**Comment by loic-sharma** [comment]
>Right now, even with `HardDelete` set, I still get `409 - conflict` when replacing the package

This sounds like a bug. You should be able to reupload a package if you have hard deletion enabled. I'll dig into that...

**Comment by loic-sharma** [comment]
@bkraul How are you replacing the package? Are you deleting the existing package before pushing the new version up? You need to use the following flow:

```
dotnet nuget delete newtonsoft.json 1.0.0 -s http://localhost:5000/v3/index.json
dotnet nuget push .\newtonsoft.json.1.0.0.nupkg  -s http://localhost:5000/v3/index.json
```

Do you want to be able to replace the existing package by simply pushing it again? If so, could you explain why you need this?

**Comment by bkraul** [comment]
@loic-sharma I am aware that ```HardDelete``` allows me to use that flow. However I am looking for in-place replacement for this reason:

I might be working on setting up a package, and forget to include some meta information or some of the meta information is incorrect. Rather than having to go through the process of deleting and re-uploading, I would expect my new package upload to replace what is already there, provided the name and version match. Again, this functionality is already present on systems like PhpNuget, and we use it all the time. I get it that this would be problematic in a community package manager setting, but in an internal setting it is very helpful. After all, it could be an option that could be turned on or off (off by default).

I hope this helps.

Thanks!

**Comment by loic-sharma** [comment]
Sounds good to me!

**Comment by loic-sharma** [comment]
Hello, this should be addressed by https://github.com/loic-sharma/BaGet/pull/208. For more information, see this documentation: https://loic-sharma.github.io/BaGet/configuration/#enabling-package-overwrites

Let me know what you think!
