### ISSUE TITLE
Question about Registration Route/Url

### ISSUE THREAD

**Issue by WernerMairl** [loic-sharma/BaGet#201]
I found 2 different routes/templates/urls to Registration.
Bug or Feature ?

Finding 1: 
https://github.com/loic-sharma/BaGet/blob/master/src/BaGet/Extensions/IRouteBuilderExtensions.cs#L80

```
template: "v3/registration/{id}/{version}.json"
```

Finding 2:
https://github.com/loic-sharma/BaGet/blob/master/tests/BaGet.Protocol.Tests/RegistrationClientTests.cs#L21

```
 var url = "https://api.nuget.org/v3/registration3/newtonsoft.json/index.json"
                                                 ^
```
/registration ends with "3"

**Comment by loic-sharma** [comment]
Good eyes! This is actually intended 😄 

The registration is what the NuGet client uses to look up packages' metadata. As NuGet has evolved, we've had to make breaking changes to the protocol. For example, we introduced a new version format in NuGet v3.4.0 and started compressing our registration responses in NuGet v3.6.0. To avoid breaking older clients, we maintain many registration endpoints on NuGet.org. For example, nuget.org's primary region has the following registration "hives":

* https://api.nuget.org/v3/registration3/
* https://api.nuget.org/v3/registration3-gz/
* https://api.nuget.org/v3/registration3-gz-semver2/

For more information, I recommend reading [this documentation](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#versioning) on NuGet's package metadata protocol.

So what about BaGet? BaGet only has a single registration resource, so it doesn't need to distinguish the different resources. Does that make sense? Please let me know if you have any additional questions, I'd be happy to answer them! :)
