### ISSUE TITLE
Update AWS Documentation

### ISSUE THREAD

**Issue by rue-vmom** [loic-sharma/BaGet#205]
### Describe the bug
Looks like S3 Bucket is supported in [code](https://github.com/loic-sharma/BaGet/tree/master/src/BaGet.AWS), however this page seems to mention that it is not supported: https://loic-sharma.github.io/BaGet/cloud/aws/

**Comment by loic-sharma** [comment]
Good catch, I'll add a quick tutorial on how to get started on AWS. Thanks!

**Comment by loic-sharma** [comment]
Hey I added basic documentation in https://github.com/loic-sharma/BaGet/commit/9ec87d7395be1cdfd05b6d998ff1b64496af8afe, you can check it out here: https://loic-sharma.github.io/BaGet/cloud/aws/. Please let me know if you have any additional suggestions!
