### ISSUE TITLE
Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by rdcm** [loic-sharma/BaGet#212]
`baget.env` file:

```
ApiKey=7def3e24-f496-465b-8abe-798a5d9928b0
Storage__Type=FileSystem
Storage__Path=/var/baget/packages
Database__Type=Sqlite
Database__ConnectionString=Data Source=/var/baget/baget.db
Search__Type=Database
```
docker run command (docker for windows):

`docker run --restart always --env-file ./baget.env -e "ASPNETCORE_URLS=http://*:5000" -d -p 5000:5000 -v bagedata:/var/baget anuraj/baget:latest`

push nuget command:

```
dotnet nuget push -s target_host:5000/v3/index.json -k "7def3e24-f496-465b-8abe-798a5d9928b0" ./my_package.nupkg
```

push error:

```
info : Pushing my_package.1.0.0.nupkg to 'target_host:5000/api/v2/package'...
info :   PUT target_host:5000/api/v2/package/
info :   Unauthorized target_host:5000/api/v2/package/ 136ms
error: Response status code does not indicate success: 401 (Unauthorized).
```

Dashboard available at this address: target_host:5000/

**Comment by loic-sharma** [comment]
Strange. I haven't had a change to reproduce this, but could you try again using the official image? https://hub.docker.com/r/loicsharma/baget

I'll try running BaGet on docker for Windows later to see if anything weird happens.

**Comment by rdcm** [comment]
Sorry, yes correct docker run command end with **loicsharma/baget:latest** :)

**Comment by loic-sharma** [comment]
Awesome! Out of curiosity, how did you choose the `anuraj/baget` image? Do you have any recommendations to make the official image easier to find?

**Comment by smazurov** [comment]
@loic-sharma just stars and downloads. It might help if you add [Official] to description.

**Comment by rdcm** [comment]
@loic-sharma just first hit in google

![baget_image](https://user-images.githubusercontent.com/11910763/52878801-95bf0c00-316e-11e9-9837-022a5d77b8f4.png)

**Comment by rdcm** [comment]
If you add docker hub link in README.md it will be more helpfull.

**Comment by loic-sharma** [comment]
Okay I tweaked the description on Docker hub. I also added a link to the official Docker image on the homepage of the documentation.

I like your idea @rdcm to add a link in the README. Ideally, the entire Docker instructions would be right on the REAMDE, but before I do that, I'd like to streamline the experience a little.
