### ISSUE TITLE
V2 protocol read through caching

### ISSUE THREAD

**Issue by phaza** [loic-sharma/BaGet#215]
### Is your feature request related to a problem? Please describe.
More and more component providers are moving to providing their commercial components through private nuget feeds. Unfortunately, it seems many of them seem to prefer (or rely on a product that only implements) the V2 protocol.
To the best of my knowledge, it seems BaGet needs a V3 service index to be able to use read-through caching/mirroring.

### Describe the solution you'd like
Support reading V2 indices.

### Describe alternatives you've considered
Handle mirroring outside BaGet.
Transform a V2 index to a V3 index for Baget

**Comment by loic-sharma** [comment]
Hello, this was added by: https://github.com/loic-sharma/BaGet/pull/630

I'll close this issue off for now, but feel free to add comments. Also, please let me know if you have any additional questions or feedback!
