### ISSUE TITLE
Use of React for UI 

### ISSUE THREAD

**Issue by DoCode** [loic-sharma/BaGet#217]
Why not use simple, 'default', 'normal' and lighweight ASP.Net Razor pages or MVC?  
Why use these fancy, overcomplicated SPA frameworks?  
BaGet doesn't use realtime UI parts or heavy interactive user navigation. BaGet doesn't benefit from this 'new' frameworks.
My opinion.

**Comment by loic-sharma** [comment]
I agree it's a little overkill today, but I'm hoping to use BaGet's UI to make a VS Code plugin to manage your NuGet packages.

**Comment by loic-sharma** [comment]
Feel free to open a new issue if you have any more suggestions or feedback
