### ISSUE TITLE
Package name does not wrap but runs into right column

### ISSUE THREAD

**Issue by bkraul** [loic-sharma/BaGet#225]
### Describe the bug
When there is a package with a long name, the text does not wrap to a new line, but it runs into the right column.

### To Reproduce
1. master / latest
2. Upload a package with long name (one that is sure to not fit the content area).
4. See text from package (whether name or version), run into the right column (screenshot attached).

### Expected behavior
Package name should wrap to a new line.

### Screenshots
![image](https://user-images.githubusercontent.com/14616851/53661887-1d088700-3c27-11e9-8487-15bfd8a586e6.png)

**Comment by loic-sharma** [comment]
This should be fixed on the latest version of BaGet. Please let me know if you have any other suggestion!

**Comment by bkraul** [comment]
Just built my docker image. Works great! Thank @loic-sharma!
