### ISSUE TITLE
Authentication for mirrors / read through caching

### ISSUE THREAD

**Issue by simmdan** [loic-sharma/BaGet#229]
### Is your feature request related to a problem? Please describe.
I want to use BaGet as a read-through cache so that I can restore nuget packages while online, then go offline and be able to restore again successfully.  Unfortunately, while most of my nuget packages come from nuget.org, some packages come from private feeds that require authentication.

### Describe the solution you'd like
I'd like to be able to specify a username and password as part of setting up the mirror options in appsettings.json and have that be used when downloading packages from the remote source if the package isn't found locally.

### Describe alternatives you've considered
Another option would be to read the nuget.config file to get this information the same way the nuget client does or to try to use the nuget client itself to do the download.  Those solutions seem like they would be more involved than duplicating this configuration information next to the mirror package source url in appsettings.json

### Additional context
In the absence of some other idea, I intend to implement this feature for my use in a fork of BaGet and will be happy to create a pull request if you would be interested in adding that capability to the main project.  Chances are, though, that I will only have time to implement basic authentication using username and cleartextpassword--not support for apikeys and encrypted passwords unless those turn out to be quite easy to include.

**Comment by smazurov** [comment]
you can also set up a reverse proxy that simply authenticates for you.

**Comment by simmdan** [comment]
Can you elaborate a bit?  I don't actually control the private feeds directly.  In fact they are VSTS (aka Azure DevOps) nuget feeds which require authentication for the downloads.

Would this be a reverse proxy server setup in-between BaGet and the remote feeds so that BaGet would send requests to the reverse proxy server which would then send them on but with authentication headers added?  Is there a suggested reverse proxy implementation?

**Comment by smazurov** [comment]
so you set up one of many available [reverse proxies](https://github.com/ilanyu/ReverseProxy), run that locally, it forwards to your nuget feed that you use basic auth with.

**Comment by loic-sharma** [comment]
I like this idea. I didn't know Azure DevOps supported basic auth for their feeds, do you have more information on this? My understanding was that all their authentication was through their plugin: https://github.com/Microsoft/artifacts-credprovider

**Comment by simmdan** [comment]
The plugin can be used, but it assumes that your local machine account is associated with an Azure Active Directory account or that it can pop up a dialog to ask you for account and password and then store that info locally.

They also support using standard Basic Auth where the value for the header is base64 encoded “<username>:<password>” and the password is a Public Access Token that you can get for your account (with whatever subset of permissions you like) in the Azure DevOps web UI.  That’s the approach my team uses.

I started investigating what it would take to make the code changes.  It seems straightforward to add the configuration options for storing the username and password, and I can set the authorization header on HttpClient, but I ran into another snag for my particular use case:

We actually use a combination of several nuget feeds all configured in our solution’s nuget.config file—including both the main public nuget.org feed and several private feeds on Azure DevOps.  Right now BaGet’s read-through mirror assumes you only have one nuget feed to configure that way.  I started to look into making BaGet check a series of feeds in order the way nuget client does and then cache packages from whatever feed it finds, but it looks a bit more complicated than I had anticipated.  First, does BaGet request the entire index of the remote server every time or is there a way that it requests a list of versions for a particular package?  Once I get over that hurdle, though, I guess I will need to determine which feed actually has a particular package and then communicate the auth info as well as the URI to the downloader since different feeds can have different auth info.

Another approach I have considered is just making the simple change to add auth with a single mirror and then running multiple instances of BaGet—one for each mirror.  It seems a bit hacky, but it might get me going significantly faster…

**Comment by simmdan** [comment]
It turns out that I have come up with a significantly simpler way to achieve my scenario.  May not be the right thing for some others, but it addresses my need without actually using BaGet at all.  What I plan to do is this (I use powershell so below syntax is for it):

```
nuget locals all -clear
dotnet restore my.sln
mkdir \offline-nuget
cd ~\.nuget\packages
dir -r -i *.nupkg |% { copy $_ \offline-nuget }
<modify nuget.config next to my sln to remove all feeds except one which is just the local file path \offline-nuget>
```

I have confirmed that this will download all the packages needed to build my sln from whatever feeds they are in using my existing authentication setup, and once I’m done all those packages are available offline and future nuget restores will just pick up the packages locally.

So I'm going to close this issue.  If someone still wants simple auth support for a single mirror src, I can help with that.  It seems pretty straightforward, but it's not enough to deal with my scenario, and the above workflow will address it.  So I'm not planning to make a PR to BaGet unless someone really wants me to.
