### ISSUE TITLE
Package managers FindPackagesById URI404

### ISSUE THREAD

**Issue by aateeque** [loic-sharma/BaGet#232]
### Describe the bug
In Visual Studio 404 error for packages that actually exist in Baget

### To Reproduce
1. Using this version of BaGet 'e342ceecdb'
2. Run this code 'dotnet Baget.dll'
3. With these arguments 'NA'

### Expected behavior
The package should be found and should install in the project

### Additional context
The full URL looks like: http://localhost:2525/api/v3/search/FindPackagesById()?id='ExamplePkg'&semVerLevel=2.0.0

**Comment by loic-sharma** [comment]
Hello, this is expected as currently BaGet does not support NuGet's V2 APIs. How are you downloading your packages? Maybe you can use NuGet's V3 APIs instead?

For your information, this issue is tracking NuGet's V2 APIs: https://github.com/loic-sharma/BaGet/issues/43
