### ISSUE TITLE
Running Baget On Linux Server

### ISSUE THREAD

**Issue by ramx** [loic-sharma/BaGet#234]
Hi,
I've installed dotnet core 2.2 and tried running Baget, but I can access the Nuget Server from other machines.
How can I access my feed from other machines?

Regards,
Ram

**Comment by 0xlc** [comment]
run "netstat -ntlp" and check if baget is listening only on 127.0.0.1

then set:

ASPNETCORE_URLS=http://0.0.0.0:5000

as env variable in your ~/.profile or /etc/profile and restart baget

check again with netstat there should be 0.0.0.0 

you can change 0.0.0.0 with the machine's ip.

and of course enable 5000 or the port you are using in the firewall.

**Comment by ramx** [comment]
I set the ASPNETCORE_URLS

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      13582/dotnet
tcp        0      0 127.0.0.1:5001          0.0.0.0:*               LISTEN      13582/dotnet

but still not able to access it :(

**Comment by 0xlc** [comment]
did you source profile again to read the new variable?

source /etc/profile or ~/.profile

or just run

export ASPNETCORE_URLS=http://0.0.0.0:5000

but it's only runtime, you'll lose it at the next reboot

**Comment by loic-sharma** [comment]
Hey I'm not very familiar with running .NET Core services from Linux, so I won't be much help here. I'd recommend reading ASP.NET Core's official hosting documentation: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-2.2

Please let me know if you have any issues specific to BaGet, I'd be happy to help with those :)

**Comment by WernerMairl** [comment]
In my experience this issue has nothing to do with BaGet or Dotnet , it is about Linux hosting, firewall etc.
I must assume that every default sample from other platforms (nginx etc) is failing on the same way.

It is really complicated for us to help here :-(

btw.: i have started a BaGet Instance on Linux/Docker AppServices yesterday, without any problems....

**Comment by ramx** [comment]
Thanks @0xlc worked with source ~/.profile

 netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      5770/dotnet
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3681/sshd
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      6367/[ready] gunico
tcp        0      0 0.0.0.0:5433            0.0.0.0:*               LISTEN      20463/postgres
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      789/master
tcp6       0      0 :::5433                 :::*                    LISTEN      20463/postgres
tcp6       0      0 :::25                   :::*                    LISTEN      789/master

Appreciate your help guys!!
