### ISSUE TITLE
PowerShell modules breaks page width

### ISSUE THREAD

**Issue by OCram85** [loic-sharma/BaGet#253]
### Describe the bug
Hosting PowerShell modules with BaGit breaks page width caused by tag list

### To Reproduce
1. Using BaGit version `v0.1.75-prerelease`
  - installed on fresh ubuntu 18.04 lts VM with dotnet-core.2.2 sdk
2. Configure nginx as proxy via:

````nginx
server {                              
  client_max_body_size 100M;          
  listen 80;                          
  server_name baget;                  
  location / {                        
    proxy_pass http://localhost:5000/;
  }                                   
}                                     
````

3. Publish any PowerShell Module like `WinSCP`
4.  Page width increases with every exported Powershell cmdlet/function.

### Expected behavior
There should be a shorted version of the tag list or a dedicated page listing all the tags

### Screenshots
![Imgur](https://i.imgur.com/JzsbOSn.png)

### Additional content

If you try to shorten the module tags by providing the paramerter `-tags` this content will be added to the default values. This means the tags will be pared like this: `<tag param values>, <exported function list>`

**Comment by loic-sharma** [comment]
Hello, this should be fixed on the latest version of BaGet. Thanks for reporting this, please let me know if you have any other suggestions!
