### ISSUE TITLE
Import package from an existing Nuget.Server instance 

### ISSUE THREAD

**Issue by muus84** [loic-sharma/BaGet#264]
### Is your feature request related to a problem? Please describe.
I'm am trying to do import all packages from our NuGet.Server instance, cause I want to replace it with a BaGet server. 

### Describe the solution you'd like
It would be great to get an option which downloads all packages from an nuget package server (api v2) to make them available on the BaGet server. 

#### Fallback idea
Provide a way to import nuget package from a folder structure created by the NuGet.Server. 

Best regards

Stefan

**Comment by loic-sharma** [comment]
Hello, here's how you import packages from an existing NuGet.Server instance:

1. [Install nuget.exe](https://www.nuget.org/downloads)
1. Navigate to the directory containing your NuGet.Server's `web.config` file using powershell
1. Run `$source = "<NuGet.Server package source>"`
1. Run `$destination = "<BaGet package source>"`
1. Run:

```ps1
if (!(Test-Path "Web.config")) {
  throw "Please run this script in the same directory as NuGet.Server's Web.config file"
}

(& nuget.exe list -AllVersions -Source $source).Split([Environment]::NewLine) | % {
  $id = $_.Split(" ")[0].Trim()
  $version = $_.Split(" ")[1].Trim()

  $path = [IO.Path]::Combine("Packages", $id, $version, "${id}.${version}.nupkg")

  Write-Host "nuget.exe push -Source $destination ""$path"""
  & nuget.exe push -Source $destination $path
}
```

I'll add this to BaGet's official documentation. Please let me know if you run into any issues!

**Comment by muus84** [comment]
Hello, thanks for creating the script. 

I have extended it a bit and created a .ps1 file. I have added a variable for the **path** to the nuget.exe, a variable for the **apikey** you need to push the packages to the BaGet server and a **file size limit**. The file size limit will be checked before the package will be pushed to prevent an error caused by to large packages. 

```powershell
$source = "<NuGet.Server package source>"
$destination = "<BaGet package source>" 
$nugetPath = 'C:\PATH\TO\nuget.exe'
$apiKey = "<BAGET_API_KEY>"
$fileSizeLimit = 10Mb 

if (!(Test-Path "Web.config")) {
  throw "Please run this script in the same directory as NuGet.Server's Web.config file"
}

(& $nugetPath list -AllVersions -Source $source).Split([Environment]::NewLine) | % {
  $id = $_.Split(" ")[0].Trim()
  $version = $_.Split(" ")[1].Trim()

  $path = [IO.Path]::Combine("Packages", $id, $version, "${id}.${version}.nupkg")

  if ((Get-Item $path).Length -le $fileSizeLimit) { 
      Write-Host "nuget.exe push -Source $($destination) $($path)"
      & $nugetPath push -Source $destination $path -ApiKey $apiKey      
   }
   else {
      Write-Warning "Error: file $($path) is bigger than $($fileSiteLimit)"
   }  
}
```
