### ISSUE TITLE
Allow PackageDeletionBehavior through environment variables

### ISSUE THREAD

**Issue by fglaeser** [loic-sharma/BaGet#275]
I'm running buget in a container platform (OpenShift), and I'd like to configure the deletion behavior through an environment variable.
Thanks

**Comment by loic-sharma** [comment]
This should work, did you try setting creating an environment variable with the name `PackageDeletionBehavior` and value `HardDelete`? BaGet's uses ASP.NET Core's configuration libraries, which supports environment variables. For more information, please refer to the ASP.NET Core documentation:  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2

**Comment by loic-sharma** [comment]
Feel free to open a new issue if you have additional questions!
