### ISSUE TITLE
Dont Delete Package in DB

### ISSUE THREAD

**Issue by lauchacarro** [loic-sharma/BaGet#278]
### Describe the bug
When I Delete a package in nuget with cmd, 

![image](https://user-images.githubusercontent.com/28534415/58827371-40bddd80-8619-11e9-8dfe-858200b2e924.png)

don´t delete in the database

![image](https://user-images.githubusercontent.com/28534415/58827250-f0df1680-8618-11e9-9096-2e91d8f54fbf.png)

this produces 409 error when i push same package with same version

![image](https://user-images.githubusercontent.com/28534415/58827391-4d423600-8619-11e9-86df-7f7696fdda08.png)

but if i delete manually this package in database 
![image](https://user-images.githubusercontent.com/28534415/58827482-837fb580-8619-11e9-9b19-3e23801d98e2.png)

this push successfully

![image](https://user-images.githubusercontent.com/28534415/58827522-a0b48400-8619-11e9-8a2c-93b77e96a280.png)

**Comment by loic-sharma** [comment]
To prevent [the "left pad" problem](https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm), BaGet's default configuration doesn't allow package deletions. Whenever BaGet receives a package deletion request, it will instead "unlist" the package. An unlisted package is undiscoverable but can still be downloaded if you know the package's id and version. You can override this behavior by setting the [`PackageDeletionBehavior`](https://loic-sharma.github.io/BaGet/configuration/#enabling-package-hard-deletions)
