### ISSUE TITLE
Too many database connections are opened to baget database

### ISSUE THREAD

**Issue by Marusyk** [loic-sharma/BaGet#282]
Why there are so many connection are opened if nobody download any packages at this  time?

### To Reproduce
1. Using this version of BaGet in docker 'baget:873b133c619e2bc048bbedc5a7fa8007c688eaf8'
2. Using PostgreSQL
3. See active connections and filter it for baget datase:

```
SELECT * FROM pg_stat_activity
where datname = 'baget_packages'
```

4. This query exec too many time:
```
SELECT p."Key", p."Authors", p."Description", p."Downloads", p."HasReadme", p."IconUrl", p."Id", p."IsPrerelease", p."Language", p."LicenseUrl", p."Listed", p."MinClientVersion", p."ProjectUrl", p."Published", p."RepositoryType", p."RepositoryUrl", p."RequireLicenseAcceptance", p."RowVersion", p."SemVerLevel", p."Summary", p."Tags", p."Title", p."Version"
FROM "Packages" AS p
WHERE (p."Id" = $1) AND (p."Listed" = TRUE)
ORDER BY p."Key"

```
### Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/9221694/59193292-e62eff00-8b8d-11e9-81e3-8e83b782828b.png)

The source code seems to be ok. Could you please clarify what is the problem?

**Comment by loic-sharma** [comment]
The query you listed is [this one](https://github.com/loic-sharma/BaGet/blob/e57d120349b4a5fe34dde7952daf4a5dd8e68a7a/src/BaGet.Core/State/PackageService.cs#L49), which is used in two places:

1. On package restores, when grabbing the list of available versions: https://github.com/loic-sharma/BaGet/blob/e57d120349b4a5fe34dde7952daf4a5dd8e68a7a/src/BaGet.Core.Server/Controllers/PackageController.cs#L36
2. On browsing packages on BaGet's website UI or when using Visual Studio's Package Manager UI: https://github.com/loic-sharma/BaGet/blob/e57d120349b4a5fe34dde7952daf4a5dd8e68a7a/src/BaGet.Core.Server/Controllers/Registration/RegistrationIndexController.cs#L40

Considering your query contains `p."Listed" = TRUE`, I'm guessing the second scenario is the issue. Could you see if opening a package on the website UI causes a new connection to be created? Do the connections ever decrease? What if you restart BaGet?

Thank you for the information!

**Comment by Marusyk** [comment]
Thank you for response.
I deployed BaGet into k8s cluster and no one can browsing website UI except me. It seems happens when  package restores. But I have only 5 packages and as you can see there are 75 connections. 

I've added this to connection string:
`Maximum Pool Size=20;Pooling=true;Connection Idle Lifetime=60;`

It helps for now. It is very strange why there are so many connection. 
Can it be a problem in my NuGet.Config? For example it restores some packages,  try to find it in my Baget then, if not found, go to nuget.org.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear /> 
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="BaGet" value="http://baget-pkg-xxxx.westeurope.cloudapp.azure.com/v3/index.json" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
</configuration>
```
