### ISSUE TITLE
Make listen port configurable from config

### ISSUE THREAD

**Issue by mcdis** [loic-sharma/BaGet#289]
Make listen port/urls configurable from config

**Comment by tbrillet** [comment]
Do you mean with the appsettings.json?

If so you can already do it with the standard kestrel json configuration. Here a small example:
```json
{
  "Kestrel": {
    "EndPoints": {
      "Http": {
	    "Url": "http://0.0.0.0:5556/"
	  }
	}
  },
  "ApiKey": "",
  "PackageDeletionBehavior": "Unlist",
  "AllowPackageOverwrites": false,
  [Etc.]
}

**Comment by pvandervelde** [comment]
@tbrillet is this valid for an IIS configuration as well?

**Comment by SeppPenner** [comment]
This is fixed once https://github.com/loic-sharma/BaGet/pull/525 is merged.
