### ISSUE TITLE
Cannot push package to server

### ISSUE THREAD

**Issue by VitaliiIsaenko** [loic-sharma/BaGet#293]
I cannot push a package to the server where I run a docker container with BaGet. I get the following error:
```
info : Pushing InnoData.1.0.0.nupkg to 'http://localhost:5555/api/v2/package'...
info :   PUT http://localhost:5555/api/v2/package/
info : An error was encountered when fetching 'PUT http://localhost:5555/api/v2/package/'. The request will now be retried.
info : Connection refused
info :   PUT http://localhost:5555/api/v2/package/
info : An error was encountered when fetching 'PUT http://localhost:5555/api/v2/package/'. The request will now be retried.
info : Connection refused
info :   PUT http://localhost:5555/api/v2/package/
error: Connection refused
```
What I do is:
```
dotnet nuget push -s https://my-server.com/v3/index.json -k NUGET-SERVER-API-KEY Package.nupkg
```
I ran container on the server I am pushing to as following:
```
docker run --rm --name nuget-server -p 5555:80 --env-file baget.env -v "$(pwd)/baget-data:/var/baget" loicsharma/baget:latest
```
My index.json looks like this:
```
{"version":"3.0.0","resources":   
 [{"@id":"http://localhost:5555/api/v2/package","@type":"PackagePublish/2.0.0","comment":""}, 
 {"@id":"http://localhost:5555/api/v2/symbol","@type":"SymbolPackagePublish/4.9.0","comment":""}, 
 {"@id":"http://localhost:5555/v3/search","@type":"SearchQueryService","comment":""}, 
 {"@id":"http://localhost:5555/v3/search","@type":"SearchQueryService/3.0.0-beta","comment":""}, 
 {"@id":"http://localhost:5555/v3/search","@type":"SearchQueryService/3.0.0-rc","comment":""}, 
 {"@id":"http://localhost:5555/v3/registration/","@type":"RegistrationsBaseUrl","comment":""}, 
 {"@id":"http://localhost:5555/v3/registration/","@type":"RegistrationsBaseUrl/3.0.0-rc","comment":""}, 
 {"@id":"http://localhost:5555/v3/registration/","@type":"RegistrationsBaseUrl/3.0.0-beta","comment":""}, 
 {"@id":"http://localhost:5555/v3/package/","@type":"PackageBaseAddress/3.0.0","comment":""}, 
 {"@id":"http://localhost:5555/v3/autocomplete","@type":"SearchAutocompleteService","comment":""}, 
 {"@id":"http://localhost:5555/v3/autocomplete","@type":"SearchAutocompleteService/3.0.0-rc","comment":""}, 
 {"@id":"http://localhost:5555/v3/autocomplete","@type":"SearchAutocompleteService/3.0.0-beta","comment":""}]}  
```
And I can also reach the server and see UI of BaGet.
Can you please help me with that?  What did I miss?  
P.S. Providing wrong api key has the same effect, I see the same error.

**Comment by onurvatan** [comment]
Hi Vitalii,

I checked your post from Github and I think you need to check your server permissions for 5555 port number. Check this post may help you. https://serverfault.com/a/725263

**Comment by VitaliiIsaenko** [comment]
Hi, Onur,
Thank you for your help! I have doubts about whether I have a problem with permission. I can access the application and work with its UI on the internet. What I cannot do, unfortunately, is to publish a package. 
I tried to `PUT https://my-server/api/v2/package/` (as problem says `An error was encountered when fetching 'PUT http://localhost:5555/api/v2/package/'. The request will now be retried.`) and I get 401 Unauthorized. Doesn't all this indicate that there are no problems with the firewall?
Also, I am not sure whether it is expected behavior that I have localhost mentioned in index.json.

**Comment by VitaliiIsaenko** [comment]
I had an assumption that `dotnet nuget push -s https://my-server.com/v3/index.json -k api-key package.1.0.0.nupkg` actually goes to `localhost:5555` and it is exactly what it does! (I setup a localserver on the port and the response is **Not Found**. I'm not sure why it could happen. Any ideas? @onurvatan maybe you had such a problem?

**Comment by VitaliiIsaenko** [comment]
Well, the problem is that I had to do this request instead:
```
dotnet nuget push -s https://my-server.com -k api-key package.1.0.0.nupkg
```
And then it works. Hope it'll help anyone. I still have to figure out why packages from this server are not shown and cannot be downloaded with NuGet :D
