### ISSUE TITLE
Getting Conflict error message even when package name is different.

### ISSUE THREAD

**Issue by manojmsrit** [loic-sharma/BaGet#297]
I want to push two nuget packages ( debug and release ) but getting conflict error while pushing the second one. Can you please suggest me regarding this.

Package names are Plugin.TestNugetPackage.1.0.0_Release.nupkg  and Plugin.TestNugetPackage.1.0.0_Debug.nupkg 

info : Pushing Plugin.TestNugetPackage.1.0.0_Release.nupkg to 'http://localhost:5555/api/v2/package'...
info :   PUT http://localhost:5555/api/v2/package/
info :   Conflict http://localhost:5555/api/v2/package/ 457ms
error: Response status code does not indicate success: 409 (Conflict).

Thanks ,
Manoj

**Comment by onuralp** [comment]
I'm encountering the same issue while uploading symbols. It works with neither symbols."nupkg"  nor ."snupkg" symbol package format unless you set allow package override environment variable true.

```
MyPackage.1.0.0.nupkg  - 200
MyPackage.1.0.0.symbols.nupkg - 409
```
```
MyPackage.1.0.0.nupkg  - 200
MyPackage.1.0.0.snupkg - 409
```

**Comment by loic-sharma** [comment]
Hi, are you sure the package names are different? Renaming the file doesn't rename the file, you have to modify the package's `PackageId` property. Please use a tool like [NuGet Package Explorer ](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) to modify the package's names. Please let me know if you need any additional help!
