### ISSUE TITLE
Symbols folder not found

### ISSUE THREAD

**Issue by diegoberges** [loic-sharma/BaGet#299]
### Describe the bug
When I try to upload a .snupkg nuget, I recieve an error 404.

### To Reproduce
1. Using this version of BaGet 'v0.1.77-prerelease'
2. Using this version of Nuget '5.0.2.5988'
2. Run this code 'dotnet nuget push -s http://localhost:5000/v3/index.json Prueba.7.0.11.snupkg '
3. See error

![image](https://user-images.githubusercontent.com/1833692/62123757-ea8fb280-b2c8-11e9-9778-87cbb4dfc373.png)

### Expected behavior
I think that de files (.nupkg and .snupkg) should upload to server.

### Additional context
**_All Log_**
```
$ dotnet nuget push -s http://localhost:5000/v3/index.json Prueba.7.0.11.snupkg 
info : Insertando Prueba.7.0.11.snupkg en 'http://localhost:5000/api/v2/symbol'...
info :   PUT http://localhost:5000/api/v2/symbol/
info :   NotFound http://localhost:5000/api/v2/symbol/ 110 ms 
error: Response status code does not indicate success: 404 (Not Found).
```

**Comment by loic-sharma** [comment]
Hello, this is expected behavior: you cannot push a NuGet symbols package without first pushing its corresponding NuGet package. I've opened a NuGet issue to improve this error message: https://github.com/NuGet/Home/issues/8404

Please let me know if you have any suggestions in this area! I'll close this off for now, but feel free to reply or open a new issue if needed 😄

**Comment by diegoberges** [comment]
Hello, OK, but this is my workflow, first I upload the nuget and after that I upload the symbols.

I think that, firstle, the error code must be more clearer to the user, not an 404 error.

**Comment by loic-sharma** [comment]
Ideally, the protocol is an implementation detail hidden by the NuGet client. The protocol can be unclear so long as the client provides a good experience. Also, the NuGet protocol is hard to change, as we need compatibility with existing NuGet clients.
