### ISSUE TITLE
Regular nuget packages show up in BaGet

### ISSUE THREAD

**Issue by nvoskuilen** [loic-sharma/BaGet#300]
### Describe the bug
Somehow regular/official nuget packages like Newtonsoft.Json show up in my private api-key protected BaGet server. This behavior wasn't present like 4 months ago.

### To Reproduce
1. Using this version of BaGet 'latest docker image'
2. Run this code 'via csproj file my packages are pushed on build'
```
  <Target Name="PushNuGetPackage" AfterTargets="GenerateNuspec" Condition="'$(Configuration)' == 'Release'">
    <Message Text="Push NuGet Package to NuGet Feed" Importance="high"></Message>
    <Exec Command="dotnet nuget push $(ProjectDir)bin\Release\$(PackageId).$(PackageVersion).nupkg -s http://some-baget-server-ip -k SOME-API-KEY"></Exec>
  </Target>
```

### Expected behavior
Maybe this behavior is a new feature in BaGet? But I would like to have my private packages repo to be clean and not filled with regular/official nuget packages.
Also it is remarkable that these regular/official nuget packages got pushed to my api-key protected BaGet server as there is no way the process responsible pushing these official  packages could have my api-key right?

**Comment by smazurov** [comment]
turn off mirroring

**Comment by nvoskuilen** [comment]
Thanks.

Please consider setting the default value to false for the Mirror feature.

**Comment by loic-sharma** [comment]
Thanks for reporting. This config was enabled by accident, I've reverted that with https://github.com/loic-sharma/BaGet/commit/79ab701ab16b12f3ee951e7d43ffc90a85ad3f6a. Please let me know if you have any other issues!
