### ISSUE TITLE
[Documentation] Add migration guide from Nuget.Server

### ISSUE THREAD

**Issue by BoBiene** [loic-sharma/BaGet#301]
Hi,

i like to migrate from Nuget.Server. I have a directory with a lot of nuget-packages and i wonder how i can import them into the BaGet index.

Is there any documentation about the migration path from Nuget.Server to BaGet?

thanks,
Bo

**Comment by jsreynolds** [comment]
I wish I still had the script... I had written a 10 line powershell script to loop through the directory of packages and initiate an upload to BaGet. I started by just uploading a couple, testing, and deleting and trying again. I just copied all the packages out of NuGet server.

**Comment by RobSmyth** [comment]
I want to do the same. I have BaGet up and running but we want to migrate from an existing folder V2 source. I want to migrate those packages over to the new BaGet server.

**Comment by loic-sharma** [comment]
Hello, here's how you import packages from an existing NuGet.Server instance:

1. [Install nuget.exe](https://www.nuget.org/downloads)
1. Navigate to the directory containing your NuGet.Server's `web.config` file using powershell
1. Run `$source = "<NuGet.Server package source>"`
1. Run `$destination = "<BaGet package source>"`
1. Run:

```ps1
if (!(Test-Path "Web.config")) {
  throw "Please run this script in the same directory as NuGet.Server's Web.config file"
}

(& nuget.exe list -AllVersions -Source $source).Split([Environment]::NewLine) | % {
  $id = $_.Split(" ")[0].Trim()
  $version = $_.Split(" ")[1].Trim()

  $path = [IO.Path]::Combine("Packages", $id, $version, "${id}.${version}.nupkg")

  Write-Host "nuget.exe push -Source $destination ""$path"""
  & nuget.exe push -Source $destination $path
}
```

I'll add this to BaGet's official documentation. Please let me know if you run into any issues!

**Comment by tinohager** [comment]
Create file and save it as `migrate.ps1`
```
$source = "http://oldnuget-server.mydomain.com/nuget"
$destination = "http://baget.mydomain.com:5555/v3/index.json"

if (!(Test-Path "Web.config")) {
  throw "Please run this script in the same directory as NuGet.Server's Web.config file"
}

(& .\nuget.exe list -AllVersions -Source $source).Split([Environment]::NewLine) | % {
  $id = $_.Split(" ")[0].Trim()
  $version = $_.Split(" ")[1].Trim()

  $path = [IO.Path]::Combine("Packages", $id, $version, "${id}.${version}.nupkg")

  Write-Host "nuget.exe push -Source $destination ""$path"""
  & .\nuget.exe push -Source $destination $path -ApiKey 59ade8ce-ed61-4928-86fa-548b2c59ea27
}
```

**Comment by loic-sharma** [comment]
Thanks @tinohager, I've updated the instructions to cover what to do if you've configured BaGet to require an API key.

**Comment by loic-sharma** [comment]
Hello, I've added the migration guide to the documentation: https://loic-sharma.github.io/BaGet/tools/migrate/

Please let me know if you have any feedback!
