### ISSUE TITLE
Add a landing page when there are no packages

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#303]
### Is your feature request related to a problem? Please describe.
BaGet shows an empty home page when you start it for the first time.

### Describe the solution you'd like
There should be a landing page that shows you how to get started. This page should have links to the upload page and the documentation.

**Comment by codenamejason** [comment]
Is this actually still open?

**Comment by loic-sharma** [comment]
Yup. Here are the two landing pages we could improve:

### Home page, if no packages have been uploaded

When you run BaGet for the first time, you are greeted with:

![image](https://user-images.githubusercontent.com/737941/74048796-be47a380-4987-11ea-8723-899f45399471.png)

This page feels cold and empty, we should make it fun and inviting! Also, I would like to provide a link to the upload page, a link to the documentation website, and a link to BaGet's GitHub issue tracker.

### Package page, if the package doesn't exist

If you search for a package that doesn't exist, BaGet gives a rather unhelpful message:

![image](https://user-images.githubusercontent.com/737941/74048561-4e391d80-4987-11ea-98e1-ef0ee74ba14d.png)

This error message is correct but not particularly helpful! We should add a link to the package on nuget.org, provide a link to the documentation, and suggest asking for help using BaGet's GitHub issue tracker.

**Comment by sipmann** [comment]
Is this issue under development? Or can I take it :) ?

**Comment by loic-sharma** [comment]
No one's working on this right now, feel free to take it! Please let me know if you have any questions :)

**Comment by sipmann** [comment]
Cool, I'm already working on it. It's something like the prints bellow that you have in mind? 

* Documentation links to https://loic-sharma.github.io/BaGet
* Issues/GitHub Project links to https://github.com/loic-sharma/BaGet/issues

## Index/Search without packages on the list
![image](https://user-images.githubusercontent.com/545754/84093611-b8f77580-a9c8-11ea-815c-b687a2ad0f84.png)

## Package page
![image](https://user-images.githubusercontent.com/545754/84093604-b268fe00-a9c8-11ea-8197-f940a2f3d532.png)

**Comment by loic-sharma** [comment]
Yup that looks great!

**Comment by sipmann** [comment]
The Pull request didn't closed the issue. Next time I'll use the proper keyword.

**Comment by loic-sharma** [comment]
No worries. Thanks for the good work @sipmann!
