### ISSUE TITLE
baget.io is dead?

### ISSUE THREAD

**Issue by stamepicmorg** [loic-sharma/BaGet#364]
### Describe the bug
![image](https://user-images.githubusercontent.com/1307229/65839357-34bb0180-e315-11e9-8c47-966a1e8aff71.png)

### To Reproduce
1. Open domain
2. Look at "parked domain" notification

### Expected behavior
Normal working of service? @loic-sharma

### Screenshots
![image](https://user-images.githubusercontent.com/1307229/65839357-34bb0180-e315-11e9-8c47-966a1e8aff71.png)

**Comment by loic-sharma** [comment]
Yup, I'm still setting up the website. I have to build lots of infrastructure so that I can mirror the entirety of NuGet.org. You can track my progress here: https://github.com/loic-sharma/BaGet/issues/237

Let me know if you have any questions! :)

**Comment by stamepicmorg** [comment]
Ok, i just thought the site was broken 👍
