### ISSUE TITLE
Documentation: Database connection configuration

### ISSUE THREAD

**Issue by euantorano** [loic-sharma/BaGet#367]
The current documentation lacks any detail relating to configuring the database to use. There is a brief mention of the environment variables in the Docker Quick Start, but no further information.

**Comment by loic-sharma** [comment]
Whoops, that's a huge gap in the docs 👀

**Comment by loic-sharma** [comment]
Added by https://github.com/loic-sharma/BaGet/pull/368. Thanks for the contribution!
