### ISSUE TITLE
Display issue: Depedencies formatting

### ISSUE THREAD

**Issue by euantorano** [loic-sharma/BaGet#369]
### Describe the bug

The dependencies list when viewing a package has a weird formatitng issue - the version constraint starts with a `[` but closes with a `)` and there is a trailing comma. It's probably best to just see the below screenshot.

### Screenshots

![Capture](https://user-images.githubusercontent.com/748913/65988996-c85d1100-e480-11e9-8881-d2f584ffb6a2.PNG)

**Comment by euantorano** [comment]
I've just double checked the database, and the data is actually stored in this odd format:

| Id | VersionRange | TargetFramework | PackageKey |
| --- | --- |
| NETStandard.Library | [1.6.1, ) | netstandard1.4 | NULL |

**Comment by loic-sharma** [comment]
Thanks for opening this! NuGet.org cleans up the text and makes the dependency a link:

![image](https://user-images.githubusercontent.com/737941/66009881-50d3b580-e471-11e9-9ab5-49e9f7a6942f.png)

I think I'll follow that model too. Let me know if you have more suggestions, I plan to invest in the UI as part of https://github.com/loic-sharma/BaGet/issues/237

**Comment by euantorano** [comment]
Yeah, that looks good to me. Might as well keep it similar to nuget.org to ease the transition for people.

**Comment by yzhoholiev** [comment]
@euantorano actually, t's a valid Nuget Package Versioning format https://docs.microsoft.com/en-us/nuget/concepts/package-versioning

**Comment by euantorano** [comment]
@yzhoholiev Yeah I realized that in https://github.com/loic-sharma/BaGet/issues/369#issuecomment-537171056 - it's just that displaying that raw string isn't the best user experience in my opinion.

**Comment by loic-sharma** [comment]
This is fixed in https://github.com/loic-sharma/BaGet/pull/375. If you'd like, you can build the latest code or use the latest Docker image (I will update the NuGet packages and GitHub release when v0.2.0-preview2 is shipped). Please let me know if you have any other suggestions or find any other bugs!
