### ISSUE TITLE
EndpointSuffix for azure

### ISSUE THREAD

**Issue by rwecho** [loic-sharma/BaGet#394]
I' m azure user from china. my azure storage account is different from global azure.
so there is a property EndpointSuffix can identity it.
We will add it in next version? 

``` csharp
    return new CloudStorageAccount(
                    new StorageCredentials(
                        options.AccountName,
                        options.AccessKey),
                    useHttps: true,
                    endpointSuffix:options.EndpointSuffix);
```

Thanks in advance.

**Comment by loic-sharma** [comment]
Ah interesting, I've never used that before. I'll add support for using a full connection string. Thanks for the suggestion!

**Comment by loic-sharma** [comment]
Just out of curiosity, how do you plan to use BaGet on Azure China?

**Comment by rwecho** [comment]
@loic-sharma  I develop BaGet in a docker with my virtual machine. 
The machine os is debian 10.

**Comment by rwecho** [comment]
So glad for supporting full connection string. Thanks .

**Comment by loic-sharma** [comment]
Hello, this will be addressed by: https://github.com/loic-sharma/BaGet/pull/411/files

**Comment by loic-sharma** [comment]
Hi, could you update to the latest version of BaGet and try out the connection string? Please let me know what you think!

For more information, check out the docs: https://loic-sharma.github.io/BaGet/quickstart/azure/#azure-blob-storage

**Comment by rwecho** [comment]
@loic-sharma  I test, it works. thanks.
