### ISSUE TITLE
Track code coverage

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#397]
### Is your feature request related to a problem? Please describe.
BaGet V1 should ship with decent code coverage.

### Describe the solution you'd like
Add coverlet: https://github.com/tonerdo/coverlet

**Comment by MarkZither** [comment]
first time I have set coverlet up so there might be things to fine tune, but there is output https://dev.azure.com/sharml/BaGet/_build/results?buildId=1162&view=codecoverage-tab

**Comment by loic-sharma** [comment]
Thanks for adding this @MarkZither!
