### ISSUE TITLE
semver 2.0 package is not in search result

### ISSUE THREAD

**Issue by Ivony** [loic-sharma/BaGet#401]
if a package referrenced a semver 2.0 pacakge, that it will not in search result.

Cause:
https://github.com/loic-sharma/BaGet/blob/a96c134b8368fbf04b56400faa91aea2892bcf74/src/BaGet.Core.Server/Controllers/SearchController.cs#L31

by default, semVerLevel value is null, includeSemVer2 value will be false,.

Proposal:
list package that with semver 2.0 by default.

**Comment by Ivony** [comment]
or add an option(like checkbox, toogle) in UI

**Comment by loic-sharma** [comment]
Where are you not seeing the search results? The UI should include SemVer 2 packages (see [this](https://github.com/loic-sharma/BaGet/blob/master/src/BaGet.UI/src/SearchResults.tsx#L246)). What is your database provider? What is your search provider? 

BaGet's search API follow's the NuGet protocol, which requires that [SemVer 2 packages are filtered by default](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#request-parameters):

> The semVerLevel query parameter is used to opt-in to SemVer 2.0.0 packages. If this query parameter is excluded, only packages with SemVer 1.0.0 compatible versions will be returned (with the standard NuGet versioning caveats, such as version strings with 4 integer pieces). If semVerLevel=2.0.0 is provided, both SemVer 1.0.0 and SemVer 2.0.0 compatible packages will be returned.

**Comment by Ivony** [comment]
in web UI. 

type package id in search box, and is not list package if it's semver2.

![snapshot-1](https://user-images.githubusercontent.com/521283/67613066-b77f9100-f7db-11e9-8388-20d28f99a0cd.png)


the pacakge search request is not provide semVerLevel parameter.

**Comment by loic-sharma** [comment]
Those HTTP search requests look incorrect. Are you on an old version of BaGet? Could you try upgrading to the latest version?

**Comment by Ivony** [comment]
Oh, it's my fault.

I'm just updated binary files.

**Comment by loic-sharma** [comment]
Glad it works for you now 😊
