### ISSUE TITLE
Enabling Read-Through Caching via environment variable for Docker

### ISSUE THREAD

**Issue by edouardberthe** [loic-sharma/BaGet#429]
It would be great to be able to have Read-through caching enabled even with the Docker version.
Maybe by adding and using two environment variables like:
```
Mirror__Enabled=true
Mirror__PackageSource="https://api.nuget.org/v3/index.json"
```
Or simply the second one (as its presence or absence would determine the mirro enabling/disabling

**Comment by Shamus03** [comment]
That should already work - I'm doing it that way and it is properly behaving as a read-through cache.  .NET's configuration framework can also read from environment variables with double-underscores separating object names.

**Comment by loic-sharma** [comment]
Yup, what @Shamus03 said is correct. Did that work for you @edouardberthe?

I should update the documentation to clarify how to modify BaGet's configurations using environment variables.

**Comment by Shamus03** [comment]
@edouardberthe some example commands to use:

Via exported variables:

```bash
$ export Mirror__Enabled=true
$ export Mirror__PackageSource="https://api.nuget.org/v3/index.json"
$ docker run \
  --rm \
  --name nuget-server \
  -p 5555:80 \
  --env Mirror__Enabled \
  --env Mirror__PackageSource \
  -v "$(pwd)/baget-data:/var/baget" \
  loicsharma/baget:latest
```

Directly setting the values:

```bash
$ docker run \
  --rm \
  --name nuget-server \
  -p 5555:80 \
  --env Mirror__Enabled=true \
  --env Mirror__PackageSource="https://api.nuget.org/v3/index.json" \
  -v "$(pwd)/baget-data:/var/baget" \
  loicsharma/baget:latest
```

Or use an env file:

```bash
$ cat baget.env
Mirror__Enabled=true
Mirror__PackageSource="https://api.nuget.org/v3/index.json"
$ docker run \
  --rm \
  --name nuget-server \
  -p 5555:80 \
  --env-file baget.env
  -v "$(pwd)/baget-data:/var/baget" \
  loicsharma/baget:latest
```

The second command is pulled straight from the [documentation](https://loic-sharma.github.io/BaGet/quickstart/docker/)

**Comment by loic-sharma** [comment]
I'll close this issue for now as I think @Shamus03's answer is spot on. @edouardberthe, feel free to open a new issue if you run into any additional issues!
