### ISSUE TITLE
Can't locate include directory 'XXXX \ 1.0.0 - beta - 63127-02 \ build \ Microsoft build. The Tasks. The Git. The targets of the repository.

### ISSUE THREAD

**Issue by BootsShu** [loic-sharma/BaGet#430]
![image](https://user-images.githubusercontent.com/31271052/70112658-fd5c2e80-1690-11ea-9c1d-6992d60230d7.png)

请问这个问题，需要怎么处理呢！谢谢！

**Comment by loic-sharma** [comment]
Weird, I've never seen this before. Do you know how to reproduce this issue? Do you have git installed on your machine?

**Comment by BootsShu** [comment]
Installed the git.

**Comment by loic-sharma** [comment]
Are you still running into issues? If so, could you send me a [binlog of your build](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md)?

1. Make sure you've installed the [.NET Core SDK](https://dotnet.microsoft.com/download)
1. Navigate to BaGet
1. Build BaGet using `dotnet build /bl`
1. This will create a file named `msbuild.binlog`. Please send that to me

**Comment by loic-sharma** [comment]
I think I figured it out - did you download the source code from the GitHub release? If so, this issue will be fixed by https://github.com/loic-sharma/BaGet/pull/434

**Comment by loic-sharma** [comment]
This has been fixed by the latest release. Please let me know if you have any additional issues or feedback!
