### ISSUE TITLE
using BaGet offline creates infinite loop without backoff for package icons

### ISSUE THREAD

**Issue by stefanloerwald** [loic-sharma/BaGet#431]
### Describe the bug
When the machine BaGet is running on loses internet connection, loading the index page leads to an infinite loop of errors trying to load the package icons. Ideally, the attempts to load the icons should be tried with exponential backoff, not immediately after it failed.

### To Reproduce
1. Set up BaGet, having at least one package present
2. Disconnect internet (can also be emulated by setting offline mode in browser dev tools after the initial page load, but that's a little bit difficult to time)
3. Load the page
4. See error in dev tools:
Request to https://www.nuget.org/Content/gallery/img/default-package-icon-256x256.png fails in endless loop.

### Expected behavior
The immediate retry also leads to "flashing" of the icon area. So implementing exponential backoff would be appropriate for any external component.

**Comment by loic-sharma** [comment]
Thanks for reporting this! This should be fixed by https://github.com/loic-sharma/BaGet/pull/435

**Comment by loic-sharma** [comment]
This has been fixed by the latest release. Please let me know if you have any additional issues or feedback!

**Comment by stefanloerwald** [comment]
Confirmed to be fixed. Great work, Thanks!
