### ISSUE TITLE
[UI] Packages without exactly 3 semver digits fail

### ISSUE THREAD

**Issue by Shamus03** [loic-sharma/BaGet#433]
### Describe the bug
The UI breaks when trying to display any package who's version does not follow the form "a.b.c".  For example a package with version "1.2.3.4".

The error comes from a call to `semver.gt` to sort package versions.  The `semver` package is very strict about version numbers, so it breaks in this case.  There is a `semver.coerce` function that does its best effort to turn a version string into a "valid" version, and I would recommend using that to at least keep the UI working.

### To Reproduce
1. Using the latest version of BaGet
2. In the UI, navigate to a package that uses four-digit semantic versions (`NUnit` is an example)
3. Notice the following error in the developer console:
```
Failed to load package. TypeError: Invalid Version: 2.5.9.10348
    at new f (semver.js:256)
    at g (semver.js:596)
    at v (semver.js:638)
    at t.value (DisplayPackage.tsx:325)
    at DisplayPackage.tsx:123
```
4. The page fails to load.

### Expected behavior
No error.

**Comment by loic-sharma** [comment]
Thanks for the report! This should be fixed by https://github.com/loic-sharma/BaGet/pull/436

**Comment by Shamus03** [comment]
I just got around to testing this on our servers.  Thanks!
