### ISSUE TITLE
Saving the Package Dependency of a target Framework fails when id is null

### ISSUE THREAD

**Issue by bqstony** [loic-sharma/BaGet#44]
Reproducion:
- Blank baget.db
- create a new c# class library (based on netstandard 2.0)
- latest sdk tools
- try to dotnet nuget push ..\ClassLibrary1\bin\Debug\ClassLibrary1.1.0.0.nupkg -s http://localhost:50561/v2/package

The error is: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'NOT NULL constraint failed: PackageDependencies.Id'.

see:
https://github.com/loic-sharma/BaGet/blob/d5f957c87fb21990b1ed500fb5a59a798c47f1fd/src/BaGet.Core/Services/IndexingService.cs#L192

But i think null is correct ...(https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery.Core/Entities/PackageDependency.cs)

**Comment by loic-sharma** [comment]
Thanks for reporting! You'll need to recreate your database as I recreated the initial migration.

Please let me know if you run into anything else, or if you have any feature suggestions!
