### ISSUE TITLE
Keep published date on NuGet.Server repository migration

### ISSUE THREAD

**Issue by beppler** [loic-sharma/BaGet#456]
I followed the instructions to migrate from [NuGet.Server ](https://loic-sharma.github.io/BaGet/tools/migrate/) and it worked well.

But All of them had the date configured to the import date. 

There is any way to keep the publish date on packages migrated?

**Comment by beppler** [comment]
I made the following powershell script that loads the published date from the Nuget Server feed and generate the SQL scripts to update the BaGet database.

```powershell
$source="<NuGet.Server package source>/Packages"
$skip = 0
do {
    $pkgs = Invoke-RestMethod $source -Method Get -Body @{ '$skip' = $skip }

    $pkgs | % {
        $published = ([DateTime]$_.published).ToUniversalTime().ToString("yyyy-MM-ddThh:mm:ss.ffffff")
        $query = "UPDATE Packages SET Published=`"{0}`" WHERE Id=`"{1}`" AND Version=`"{2}`";" -f $published,$_.Properties.id,$_.Properties.NormalizedVersion
        Write-Host $query
    }

    $skip = $skip + 25
}
until ($pkgs.Count -lt 25)
```

**Comment by loic-sharma** [comment]
I'm glad you were able to unblock yourself! For now I'll refer anyone that has a similar question to your comment. In the future I'd like to add better tooling to migrate from different NuGet servers and keep the metadata intact. Please let me know if you run into any additional problems!
