### ISSUE TITLE
Cannot delete packages b/c version is incorrectly case sensitive 

### ISSUE THREAD

**Issue by jcoburn** [loic-sharma/BaGet#458]
### To Reproduce
1. Using this version of BaGet BaGet.dll reports version 1.0.0.0 2/5/2020, this is latest download 
2. Run this code 
C:\LocalCache> DotNet nuget push LandisGyr.AMI.ReadingTypes.1.0.0-Alpha0002.nupkg --api-key landisgyr --source http://localhost:5000/v3/index.json --symbol-source http://localhost:5000/v3/index.json --no-service-endpoint                 info : Pushing LandisGyr.AMI.ReadingTypes.1.0.0-Alpha0002.nupkg to 'http://localhost:5000/api/v2/package'...
info :   PUT http://localhost:5000/api/v2/package/
info :   Created http://localhost:5000/api/v2/package/ 876ms
info : Your package was pushed.
PS C:\LocalCache> DotNet nuget push LandisGyr.AMI.ReadingTypes.1.0.0-Alpha0003.nupkg --api-key landisgyr --source http://localhost:5000/v3/index.json --symbol-source http://localhost:5000/v3/index.json --no-service-endpoint                 info : Pushing LandisGyr.AMI.ReadingTypes.1.0.0-Alpha0003.nupkg to 'http://localhost:5000/api/v2/package'...
info :   PUT http://localhost:5000/api/v2/package/
info :   Created http://localhost:5000/api/v2/package/ 243ms
info : Your package was pushed.
PS C:\LocalCache> dotnet nuget delete LandisGyr.AMI.ReadingTypes 1.0.0-Alpha0002 --source http://localhost:5000/v3/index.json  --api-key landisgyr                                                                                              LandisGyr.AMI.ReadingTypes 1.0.0-Alpha0002 will be deleted from the 'http://localhost:5000/api/v2/package'. Would you like to continue? (y/N)
y
warn : Deleting LandisGyr.AMI.ReadingTypes 1.0.0-Alpha0002 from the 'http://localhost:5000/api/v2/package'.
info :   DELETE http://localhost:5000/api/v2/package/LandisGyr.AMI.ReadingTypes/1.0.0-Alpha0002
info :   NotFound http://localhost:5000/api/v2/package/LandisGyr.AMI.ReadingTypes/1.0.0-Alpha0002 238ms
error: Response status code does not indicate success: 404 (Not Found).
PS C:\LocalCache>        

Delete failed.

output from DotNet baget.dll
PS C:\Users\jcoburn\Downloads\BaGet3.1> del .\baget.db
PS C:\Users\jcoburn\Downloads\BaGet3.1> dotnet BaGet.dll
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\jcoburn\Downloads\BaGet3.1
warn: BaGet.Core.PackageDeletionService[0]
      Could not find package LandisGyr.AMI.ReadingTypes 1.0.0-Alpha0002

### Expected behavior

expected version Alpha0002 to be deleted.  Still show up in the web UI Also.

Delete baget.db and was able to reproduce.

**Comment by loic-sharma** [comment]
Thanks for reporting this! It looks like the version column is incorrectly case sensitive while using SQLite or PostgreSQL database providers. I'll release a fix for this tonight

**Comment by loic-sharma** [comment]
This was fixed in [release v0.3.0-preview2](https://github.com/loic-sharma/BaGet/releases/tag/v0.3.0-preview2). Please let me know if you have any feedback or run into any other issues!
