### ISSUE TITLE
help me ,plz  , How can i config   use an other port for dotnet run

### ISSUE THREAD

**Issue by AtlantisDe** [loic-sharma/BaGet#485]
## default --Because i download the release version.
- i don't want to Develop  so have any way to do it ??? 
```c#
 dotnet BaGet.dll
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]

```

## I want to change 
```c#
 listening on: http://localhost:6000
``` 

 
 
```html
tks very much
```

## I try  Develop
```c#
Navigate to .\BaGet\src\BaGet.UI
Install the frontend's dependencies with npm install
``` 
but hava  some error..

```c#
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\helloworld\AppData\Roaming\npm-cache\_logs\2020-03-02T05_10_49_949Z-debug.log
``` 
</details>

**Comment by softlion** [comment]
See https://github.com/aspnet/KestrelHttpServer/issues/639

**Comment by SeppPenner** [comment]
I have added this in the pull request https://github.com/loic-sharma/BaGet/pull/525. Try out this branch if you want to test. 

@AtlantisDe: By the way, don't use port 6000. It's blocked by default in all browsers: https://neo4j.com/developer/kb/list-of-restricted-ports-in-browsers/.
