### ISSUE TITLE
BaGet.UI Install the frontend's dependencies with npm install Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AtlantisDe** [loic-sharma/BaGet#486]
### Maximum call stack size exceeded
BaGet.UI 
Install the frontend's dependencies with npm install 
```c#
node --version
v13.9.0

```
```c#
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\helloworld\AppData\Roaming\npm-cache\_logs\2020-03-02T05_10_49_949Z-debug.log
```

**Comment by SeppPenner** [comment]
You should probably attach the log file. This makes it easier to finde the real issue :)

**Comment by loic-sharma** [comment]
I've never ran into this problem myself, logs would definitely help. FYI, I develop using the LTS version of nodejs, so consider downgrading.

**Comment by SeppPenner** [comment]
I had these kind of errors with Node.JS sometimes in the past. Most of the time, this occurs due to inconsistent libraries and related errors...

**Comment by kingofthebongo2008** [comment]
[2020-10-19T11_56_14_161Z-debug.log](https://github.com/loic-sharma/BaGet/files/5401574/2020-10-19T11_56_14_161Z-debug.log)
