### ISSUE TITLE
Baget doesn't allow setting Mirror options via environment variables

### ISSUE THREAD

**Issue by fourpastmidnight** [loic-sharma/BaGet#492]
### Describe the bug

The default production `appsettings.json` file explicitly disables mirroring&mdash;which is a sound, sensible default. However, due to the order in which configuration is applied in `ConfigureBagetConfiguration', with environment variables being added first, followed by the settings in `appsettings.json`, this effectively means that when running Baget in a docker container, it's impossible to change this setting.

### To Reproduce

1. Run the following commands:
    ```powershell
    docker pull loicsharma/baget:latest
    docker run `
    >> --name  baget-server -d -p 8800:80 `
    >> -e Mirror__Enabled=true -e Mirror__PackageSource=https://api.nuget.org/v3/index.json
    >> -e AllowPackageOverwrites=true `
    >> --mount type=bind,src=D:\var\opt\baget\pkgs,dst=/var/baget loicsharma/baget:latest
    ```
2. Navigate in your browser to the baget-server.
3. No NuGet.org packages show up in the interface when searching for them.

### Expected behavior

I expected to see packages from Nuget.org show up when I search for them (or even when just simply navigating to the baget server).

### Additional context

The only way to effectively do this right now is to create your own docker image based on the official baget image and add a layer which adds a modified `appsettings.json` file.

But I think this could be fixed by reordering the code [here](https://github.com/loic-sharma/BaGet/blob/9c5a9f38896a5b70f6bc66b17c1c94543af39c2a/src/BaGet/Extensions/IHostBuilderExtensions.cs#L15-L19) in `ConfigureBagetConfiguration`. Basically, lines 15 and 17 ought to be swapped such that the `appsettings.json` is loaded first, then the environment variables are loaded. In this way, if no environment variables are supplied, then the prevailing configuration in `appsettings.json` applies. But if environment variable are supplied, they can override the settings in `appsettings.json`.

I can put in a PR for this a little bit later today.

**Comment by fourpastmidnight** [comment]
Hmm, what doesn't make sense about this, though, is that in my docker container instance, I was able to change `AllowPackageOverwrites` to `true`, and it does work. So why isn't the mirroring configuration being reflected?

**Comment by fourpastmidnight** [comment]
Ah, never mind. Apparently I need to read more. This is handled natively by ASP.Net Core already. So I must have something misconfigured.

**Comment by andryushchenko** [comment]
@fourpastmidnight Have find fox for this?

**Comment by loic-sharma** [comment]
Sorry for the late reply. Like @fourpastmidnight mentioned, this should be supported natively. You should be able to use the environment variable `Mirror__Enabled` to enable mirroring (notice that there are TWO underscores between `Mirror` and `Enabled`).
