### ISSUE TITLE
I can't get caching to work, but it's because I don't understand the doc

### ISSUE THREAD

**Issue by thomasd3** [loic-sharma/BaGet#494]
I'm using the docker image and I have the baget.env file to setup the config, etc..

the only feature I need is read-through caching; essentially I want to be able to do .net builds while abroad on a crappy connection.

in the doc, at https://loic-sharma.github.io/BaGet/configuration/#enable-read-through-caching, I see:

"You can modify BaGet's configurations by editing the appsettings.json file."

but this file is part of BaGet's code, so does that mean I need to rebuild my own docker image and there is no way to set the the read through cache though an external config file?

**Comment by fourpastmidnight** [comment]
You're supposed to be able to set an environment variable: `MIRROR__ENABLED=true` and `MIRROR__PACKAGESOURCE=<URL TO PACKAGE SOURCE>`. BUT, I haven't been able to get this to work...either via Docker, or by a bare-metal install and modifying the `appSettings.json`  file. Maybe you could give it a whirl, trying to set the environment variable in your docker image container and see if it works?

**Comment by rwecho** [comment]
This is the asp.net core configuration feature. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#environment-variables-1
