### ISSUE TITLE
[UI] Add .NET Core 3.1 target framework filtering

### ISSUE THREAD

**Issue by brentjrussell** [loic-sharma/BaGet#498]
Version v0.3.0-preview1 says that is supports .NET Core 3.1.  

I am using this version from DockerHub

https://hub.docker.com/r/loicsharma/baget/tags

When I am running the docker image, I can push my .NET core 3.1 NuGet packages without an issue, but the filter option under Framework in the BaGet GUI does not show .NET Core 3.1.  It only goes to .NET core 3.0.

Maybe the dockerhub image does not support this filtering yet?

**Comment by loic-sharma** [comment]
Nice catch! I forgot to update the UI to allow users to select the .NET Core 3.1 target framework filter

**Comment by SeppPenner** [comment]
Is fixed in https://github.com/loic-sharma/BaGet/pull/527.

My issue under https://github.com/loic-sharma/BaGet/issues/526 is a duplicate then :D

**Comment by SeppPenner** [comment]
> Maybe the dockerhub image does not support this filtering yet?

The whole project doesn't support the filtering yet to be honest :D I have added this, once @loic-sharma will merge it, it's available.
