### ISSUE TITLE
Get Packages issue, When using VisualStudio Nuget Packet Maneger

### ISSUE THREAD

**Issue by Masterhame** [loic-sharma/BaGet#502]
Hi
At first I appreciate for the great project BaGet.

I'm trying to get packages from a BaGet server we Implemented lastly, using VisualStudio Nuget Packet Manager. These packages are downloaded in Package folder of my project, but they are not added to my references.
Issue is completely shown on the picture below.
please help me to solve this issue.

Regards

### Screenshot

![Baget_Problem990125](https://user-images.githubusercontent.com/15706446/79116115-dd561d80-7d9c-11ea-8f6b-ab205806a549.jpg)

**Comment by loic-sharma** [comment]
Hi, thanks for reaching out. This sounds like an issue with NuGet client. I'd suggest taking a look at their documentation (https://docs.microsoft.com/en-us/nuget/) or asking on stackoverflow.com. I'll close this for now but feel free to add additional comments if you run into problems with BaGet.
