### ISSUE TITLE
Some frameworks are missing in the filters.

### ISSUE THREAD

**Issue by SeppPenner** [loic-sharma/BaGet#526]
### Is your feature request related to a problem? Please describe.
Not a problem.

### Describe the solution you'd like
Add NetCore3.1, NetStandard2.1 and NetFramework4.8 to the filtering section.

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by loic-sharma** [comment]
Nice catch on .NET Framework 4.8, I completely forgot about that! 😀

This was fixed by #527
