### ISSUE TITLE
Nuget packages are outdated

### ISSUE THREAD

**Issue by SeppPenner** [loic-sharma/BaGet#529]
### Is your feature request related to a problem? Please describe.
Not a specific problem.

### Describe the solution you'd like
Updated the NuGet packages to the current version to avoid security issues and errors.

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by SeppPenner** [comment]
@loic-sharma Can you explain what's the idea behind the options `Version="$(MicrosoftEntityFrameworkCorePackageVersion)"` and so on? Should I leave it like it is now?

**Comment by SeppPenner** [comment]
Ah, I understand it now. Do you really want to do this with directory.props? I believe it's easier to use the Visual Studio integrated NuGet package manager...

**Comment by loic-sharma** [comment]
> Ah, I understand it now. Do you really want to do this with directory.props? I believe it's easier to use the Visual Studio integrated NuGet package manager...

Yup, this is the only way to manage package versions centrally in a cross platform way. The Visual Studio experience is currently limited and does not work well on all platforms.

Note that we (the NuGet team) are working on overhauling the centrally defined package versions experience. For more information, see: https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions

**Comment by SeppPenner** [comment]
> Yup, this is the only way to manage package versions centrally in a cross platform way.

Ah, okay. Makes sense now :)

> Note that we (the NuGet team) are working on overhauling the centrally defined package versions experience. For more information, see: https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions

Very good. Right now, since this is not supported in Visual Studio, I have to be careful 😄 Otherwise, I will update the NuGet packages by VS and overwrite the placeholders.

**Comment by SeppPenner** [comment]
So, this can be closed as the pull request is finished now and will is able to be merged soon :)
