### ISSUE TITLE
Why i can not push symbols?

### ISSUE THREAD

**Issue by LightVolk** [loic-sharma/BaGet#533]
### Describe the bug
I try to add nuget package + symbols package (snupkg) with command:

dotnet nuget push -s http://localhost:5000/v3/index.json MyPackage.1.0.
2.nupkg -k api_key

At source folder i have two files:

MyPackage.1.0.2.nupkg
MyPackage.1.0.2.snupkg

### To Reproduce
1.BaGet v0.3.0-preview2
2. dotnet nuget push -s http://localhost:5000/v3/index.json MyPackage.1.0.2.nupkg -k api_key

(2) ; also i try to use two commands:
dotnet nuget push -s http://localhost:5000/v3/index.json MyPackage.1.0.2.nupkg -k api_key
dotnet nuget push -s http://localhost:5000/v3/index.json MyPackage.1.0.2.snupkg -k api_key

Result: 

 PUT http://localhost:5000/api/v2/symbol/
 Created http://localhost:5000/api/v2/symbol/ 149 мс

### Expected behavior
I want to see MyPackage on feed with symbols, but i see package without symbols.

What i do wrong?
Thank you!

**Comment by ferarias** [comment]
Have you tried to consume the symbols? I can't see anything in the UI but when debugging from Visual Studio, symbols are obtained and used.

**Comment by loic-sharma** [comment]
Yup, @ferarias is right, the UI does not indicate whether a package has symbols (though this would be a good feature to add!). However, Visual Studio should load your symbols if you debug into your NuGet package.

If needed, you should be able to find your symbols in BaGet's storage under the folder `symbols`.

**Comment by LightVolk** [comment]
@ferarias , i go to remote folder (with packages) and i see only package with dll.
repo Step: publish nupkg packet, then - snupkg.

**Comment by LightVolk** [comment]
Sorry, i can do it! And i load symbols on my local machine!

**Comment by LightVolk** [comment]
But, how i can use Baget as symbol server?
I go to http://localhost:5000/api/download/symbols  , but see empty list.

![image](https://user-images.githubusercontent.com/1236916/85400889-cc2a4980-b561-11ea-92fb-cc43f64555fa.png)


So, i add http://localhost:5000/api/download/symbols as nuget symbols server.
Instruction: [Visual Studio instruction](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2017#configure-symbol-locations-and-loading-options)

At `d:\!Nuget\NugetTempRepo\Libs\symbols\myPackage.pdb\` i see this file: `85c1a26fde264bb5bff17dcf8a40c799ffffffff`

**Comment by loic-sharma** [comment]
First, make sure that your "Debugging" options has "Enable Just My Code" disabled.

Next, use Visual Studio's "Modules" window to check that your symbols have been loaded successfully:

1. Select "Debug" on the command bar
1. Select "Windows"
1. Select "Modules". This will open the "Modules" window.
1. In the "Modules" window, find the row for the dll you're interested in.
1. Check the value of the "Symbol status" column. It should say "Symbols loaded." If it doesn't, right click and select "Load symbols"

![image](https://user-images.githubusercontent.com/737941/85933130-4e7b7c00-b888-11ea-8278-d3794483fba0.png)

![image](https://user-images.githubusercontent.com/737941/85933160-e24d4800-b888-11ea-80de-f0c2180ed787.png)

**Comment by LightVolk** [comment]
@loic-sharma , sorry for late answer. It works! Thank you!

**Comment by loic-sharma** [comment]
Glad to hear that helped! Please let me know if you have any additional questions or feedback

**Comment by LightVolk** [comment]
@loic-sharma , can you write some todos , because i want to help project, but do not know how and what to contribute.
