### ISSUE TITLE
Version order is not enforced

### ISSUE THREAD

**Issue by chaghi** [loic-sharma/BaGet#534]
After migrating from _NuGet.Server_ to _BaGet_ ussing the [suggested script](https://loic-sharma.github.io/BaGet/tools/migrate/#migrate-from-nugetserver), we ended up with the _Versions_ section of each package in a more or less random order.

Digging up the code, I've found that the Versions views assumes the list is ordered following SemVer, and reverses it:

```tsx
  public render() {
    // Show the versions from greatest to smallest.
    // We clone the versions array to avoid modifying the props.
    // This assumes the versions are ordered by semver ascendingly.
    let versionsToRender = [...this.props.versions];
    versionsToRender.reverse();
    if (!this.state.showAll) {
      versionsToRender = versionsToRender.slice(0, Versions.defaultVisible);
    }
```

But the method `FindAsync` in `PackageService` does not enforce an order:

```csharp
        public async Task<IReadOnlyList<Package>> FindAsync(string id, bool includeUnlisted, CancellationToken cancellationToken)
        {
            var query = _context.Packages
                .Include(p => p.Dependencies)
                .Include(p => p.PackageTypes)
                .Include(p => p.TargetFrameworks)
                .Where(p => p.Id == id);

            if (!includeUnlisted)
            {
                query = query.Where(p => p.Listed);
            }

            return (await query.ToListAsync(cancellationToken)).AsReadOnly();
        }
```

So the packages end up ordered (indirectly) by `Key`. This happens to be the "correct" order, indirectly, if packages are published naturally during their lifetime, assuming each new version has a higher _SemVer_ than the previous.

But I think it would be better to enforce the assumed ordering in the service to avoid any ambiguity (like for example the one we got into after a migration). Not forcing an order could also break normal use cases: if someone publish a bugfix package for a previous (lower) major version, that version would be the first one shown in the _Versions_ section, breaking the ordering.

**Comment by loic-sharma** [comment]
Thanks for the detailed bug report! This is a great catch :)

After we load the packages from the database, we use the [`RegistrationBuilder.BuildIndex`](https://github.com/loic-sharma/BaGet/blob/bd440199ba16f62bdb0c157c69b6479f3e2aa9f9/src/BaGet.Core/Metadata/RegistrationBuilder.cs#L17) method to generate the response. This should order the packages by their versions before building the response. We should also add tests to cover this.

**Comment by chaghi** [comment]
So the fix seems to be as simple as replacing

```csharp
                        ItemsOrNull = registration.Packages.Select(ToRegistrationIndexPageItem).ToList(),
```

by

```csharp
                        ItemsOrNull = registration.Packages.OrderBy(p => p.Version).Select(ToRegistrationIndexPageItem).ToList(),
```

That way we take advantage of `NuGet.Versioning.NuGetVersion` which already knows how to sort itself, and to deal with pre-release suffixes and the like.

I was willing to submit a PR... but got turned off by the tests. Unless I'm missing something, there's no test infraestructure in place for `RegistrationBuilder` already. So I would need to start from zero, and mock and/or setup `IUrlGenerator`, `PackageRegistration`,  and a list of `Packages` with enough metadata so that `ToRegistrationIndexPageItem` and `ToDependencyGroups` can do their thing. 

Am I missing something?

**Comment by loic-sharma** [comment]
That fix sounds good to me! Personally I'd tidy up the code a little bit by removing the `versions` variable:

```
var sortedPackages = registration.Packages.OrderBy(p => p.Version).ToList();

return new BaGetRegistrationIndexResponse
{
    ...
        Lower = sortedPackages.First().ToNormalizedString().ToLowerInvariant(),
        Upper = sortedPackages.Last().ToNormalizedString().ToLowerInvariant(),
        ItemsOrNull = sortedPackages.Select(ToRegistrationPageItem).ToList()
    ...
}
```

> I was willing to submit a PR... but got turned off by the tests. Unless I'm missing something, there's no test infraestructure in place for RegistrationBuilder already. So I would need to start from zero, and mock and/or setup IUrlGenerator, PackageRegistration, and a list of Packages with enough metadata so that ToRegistrationIndexPageItem and ToDependencyGroups can do their thing.

Yes that's right. I would do the minimum test needed to cover the sorting behavior, don't worry about getting full coverage on the `RegistrationBuilder` class. I'll work on that separately from this fix :)

I apologize for the added hassle of adding tests in a new space. I'm concerned that the sorting behavior is a subtle "feature" that one may easily break in the future. Adding a unit test would ensure that we never have this subtle bug again. Please let me know if you have any questions or would like any pointers. I really appreciate the help!
