### ISSUE TITLE
Can't push package to server while using iis

### ISSUE THREAD

**Issue by itachijames** [loic-sharma/BaGet#540]
run the website on powershell, everything work fine. but when i publish it to IIS, then i can't push package to server using the nuget cmdline, it say 405 error method not allow

**Comment by itachijames** [comment]
solve it with reinstall the iis and selected all item behind iis->wwwservice->appfunc, and code in web.config
```
<system.webServer>
        <handlers>
            <remove name="WebDAV"/>
        </handlers>
        <modules>
            <remove name="WebDAVModule"/>
        </modules>
        ..
</system.webServer>
```

**Comment by loic-sharma** [comment]
I'm glad you were able to figure this out! Thanks for sharing your solution :)

Please let us know if you run into any additional problems or have suggestions!
