### ISSUE TITLE
Configuration - alternate root path for proxied container deployment

### ISSUE THREAD

**Issue by KelsonBall** [loic-sharma/BaGet#544]
I just set up BaGet using an nginx reverse-proxy to a container, under the `location /baget/`, so it is accessed at `https://example.com/baget` - but the interface seems to assume that baget is at the root of the domain. 

How can I configure BaGet to know it is not at the root of the domain?

**Comment by KelsonBall** [comment]
Update - 
I found a closed PR that appears to have added an undocumented configuration parameter PathBase: #114 

Adding `PathBase=/baget` does not seem to effect my `https://example.com/baget/v3/index.json` file. I am able to fetch the json file correctly but its data points to the root level `https://example.com/api/...` instead of the correct `https://example.com/baget/api/...` paths. 
As a result, trying to push a package using the dotnet cli fails, because the index.json points at incorrect paths.

Note: I seem to have mostly gotten the UI to work by adding the following to my docker startup script
```sh
docker exec -it nuget-server find /app/BaGet.UI/build/ -type f -exec sed -i -e 's/\/static/\/baget\/static/g' {} \;
```

**Comment by loic-sharma** [comment]
> Update -
> I found a closed PR that appears to have added an undocumented configuration parameter PathBase: #114

Yup, there's a "hidden" config `PathBase` that lets you do this for the backend. Like you noticed, the frontend doesn't properly react to this yet.

> Adding `PathBase=/baget` does not seem to effect my `https://example.com/baget/v3/index.json` file. I am able to fetch the json file correctly but its data points to the root level `https://example.com/api/...` instead of the correct `https://example.com/baget/api/...` paths.

BaGet won't generate links with the prefix `/baget` unless the requested URL also has the `/baget` prefix. You'll need to make sure that the reverse proxy includes the `/baget` prefix. For more information, see the answer here: https://stackoverflow.com/questions/45311393/asp-net-core-reverse-proxy-with-different-root

> Note: I seem to have mostly gotten the UI to work by adding the following to my docker startup script
> 
> ```shell
> docker exec -it nuget-server find /app/BaGet.UI/build/ -type f -exec sed -i -e 's/\/static/\/baget\/static/g' {} \;
> ```

That's a neat trick, thanks for sharing! I may use this idea :)

**Comment by KelsonBall** [comment]
Thank you - solution was to change my sites nginx configuration from 
```
location /baget/ {
            proxy_pass         http://localhost:[BaGet port]/;
            . . .
```
to 
```
location /baget/ {
            proxy_pass         http://localhost:[BaGet port]/baget/;
            . . .
```

After successfully adding a package though I can see that the trick for the UI definitely hasn't fixed everything 😄

**Comment by loic-sharma** [comment]
I'm glad you were able to get the backend working! Thanks for sharing your solution :)

For the UI, I would try replacing the `__BAGET_PLACEHOLDER_API_URL__` (see [this](https://github.com/loic-sharma/BaGet/blob/1070e9aca0c6eda809a3d56b9519678251d09e33/src/BaGet.UI/src/config.tsx#L2)). For example, say that your BaGet API can be found at `http://my-website/baget` you should replace __BAGET_PLACEHOLDER_API_URL__` with `http://my-website/baget`/

**Comment by nakedelement-gb** [comment]
For the BAGET_PLACEHOLDER_API_URL solution above, I assume this requires a rebuild? It can't be done as part of the configuration at runtime?

I'm looking to run BaGet as part of a suite of dev tools running with Docker Compose. I want it to run behind an Apache2 (or Nginx) reverse proxy. My Apache2 onnfig is basically this (my Docker Compose service is called baget):

ProxyPass /baget http://baget/baget nocanon
ProxyPassReverse /baget http://baget/baget nocanon

And I've added:

"PathBase": "/baget",

To appsettings.json via an intermediate Dockerfile and the example from @KelsonBall above to get the UI to display, but all the links are wrong in the UI and there are no packages displayed, etc. 

I'd really like to get the full UI working. I'm not adverse to building my own version of BaGet and pushing it to Docker Hub, but I'd prefer a configuration solution.
