### ISSUE TITLE
Package fails to upload on postgres

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#545]
From @thareek on gitter:

> Hi @loic-sharma, Hope you're doing good. when you get a chance could you please provide me info on this.
Hi.. my config has aws s3, rds postgres and the baget app is running fine (windows 10 desktop machine). Almost uploaded 20 packages and able to download it and use it as expected. one specific package push is failing at every attempt.
>
> error "Response status code does not indicate success: 500 (Internal Server Error)."
>
> say package name is "address1.01.nupkg", And when i change the rds postgres to sqllite of local in config the push is working fine.
>
> so some reference specific to this package in postgres is causing the error, so what are the options to clean up the package related details directly in postgres? Or is there logs we can check to idenity rootcause for this error ?

**Comment by loic-sharma** [comment]
Hello, thanks for reaching out! This is definitely unexpected. As a first step, please make sure to upgrade to the latest version of BaGet just in case that fixes your issue.

If upgrading doesn't help, please share a package that that reproduces this upload issue while using postgres.

> so what are the options to clean up the package related details directly in postgres?

I'm not sure I understand this question. Why do you need to clean up the package in postgres if it wasn't successfully uploaded? 

Just in case it helps, you can set the `PackageDeletionBehavior` config to `HardDelete` (see [this](https://loic-sharma.github.io/BaGet/configuration/#enable-package-hard-deletions)) and then run `nuget delete MyPackage 1.0.0 -source https://localhost:5000/v3/index.json`. This will clean up the database and storage and should get you back to a "clean" state.

> Or is there logs we can check to idenity rootcause for this error ?

BaGet should log exceptions to the console output. If needed, you can increase BaGet's verbosity by changing the verbosity config to `Informational` [here](https://github.com/loic-sharma/BaGet/blob/1070e9aca0c6eda809a3d56b9519678251d09e33/src/BaGet/appsettings.json#L36).

**Comment by thareek** [comment]
Thanks @loic-sharma . we found the rootcause for the issue, it's the package description length. 

Fix: updated the description column size in postgres DB

**Comment by loic-sharma** [comment]
Glad you were able to fix your problem! Feel free to reach out again if you have any other questions or feedback :)
