### ISSUE TITLE
Overriding endpoints in the AWS S3 storage

### ISSUE THREAD

**Issue by thomas-illiet** [loic-sharma/BaGet#551]
Hello Loic :)

Can you implement the overriding endpoint service url in the s3 storage.

I need this to use internal storage in my company.

Kind regards
Thomas

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by loic-sharma** [comment]
I'm not very familiar with this. From reading [this guide](https://aws.amazon.com/blogs/developer/overriding-endpoints-in-the-aws-sdk-for-net/), it looks like this would mean overriding the `AmazonS3Config.ServiceURL` property?

This should be pretty to do here: https://github.com/loic-sharma/BaGet/blob/68e99bf416cb547d5454d3d2b54b27e07be48091/src/BaGet.Aws/AwsApplicationExtensions.cs#L34-L37

I'd be happy to accept a pull request

**Comment by thomas-illiet** [comment]
I will try to create a pull request next week 🤪

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
