### ISSUE TITLE
Documentation error for Docker port

### ISSUE THREAD

**Issue by rvandepu** [loic-sharma/BaGet#555]
The documentation at https://loic-sharma.github.io/BaGet/installation/docker/ states:

> You can now run BaGet:
> `docker run --rm --name nuget-server -p 5555:5000 --env-file baget.env -v "$(pwd)/baget-data:/var/baget" loicsharma/baget:latest`

I tried this, but my TCP connections kept getting closed.
Then I saw port 80 was exposed by the container, That one DOES host the webserver. Published port 80, now everything works fine.

**Comment by enricobenedos** [comment]
[Documentation](https://loic-sharma.github.io/BaGet/installation/docker/) seems now ok 😉 

Can this issue be closed?

**Comment by rvandepu** [comment]
Sure, it's indeed fixed
