### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by Baklap4** [loic-sharma/BaGet#56]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Currently there's no Continuous integration. In other words this means we have to run the unit tests ourselves, check style coding etc, check if it builds. I bet we don't want that. We'd love to see this repetitive stuff to be automated as much as possible. Here comes CI around the corner.

### Expectations
The CI should be able to do:
- [ ] Be triggered upon a push (commit or tags)
- [ ] Restore dependency packages
    - Run the command `dotnet restore --packages SOME/LOCATION` in the same folder as where the `sln file` is.
- [ ] Cache the dependencies so our buildtime will decrease
    - Run the previous command with the cached packages when the pipeline builds a second time.
- [ ] Build the project
    - [ ] Windows
    - [ ] Linux
    - [ ] OSx
- [ ] Run tests
    - [ ] Windows
    - [ ] Linux
    - [ ] OSx
- [ ] Once every night run a nightly build.

If the CI meets these expectations AND the push is a tag/release CD will pop up to release a new version. see #57

**Comment by Baklap4** [comment]
@loic-sharma i'd love to set this up, however i'd need access to the webhook area of this github page

**Comment by Baklap4** [comment]
Hmm personally i'm not a big fan of VSTS, since it was so hard to configure and let it do what it should be doing. Let be creating a docker image or such.. therefore I moved to gitlab which was way easier. Here on Github most of the people do use travis or jenkins to do what they want

**Comment by WernerMairl** [comment]
I have my own CI Build System here (Jenkins, Docker, implemented in pwsh on Linux)
 
I like the idea to define/implement a few basic entry points and scripts that can be used from multiple 
CI-Systems.....

to avoid deep/hard dependencies into ONE CI-Build system, so we are open for

- VSTS (Pipeline or Classic)
- travis et. al
- custom/on premise systems

that may by a litle bit more of work, but it should bring back a lot of learnings in this area!

what you think about that ?

**Comment by loic-sharma** [comment]
Added Travis CI as part of https://github.com/loic-sharma/BaGet/commit/a4ddace43eb4ff2cca19bcd411a809e23813d358. Feel free to open another issue if you have any other ideas!

**Comment by loic-sharma** [comment]
Reopening this. The current set up doesn't run unit tests.

**Comment by loic-sharma** [comment]
Travis will now run the tests as part of the build. Closing this again. Apologies for the noise!

**Comment by kirkone** [comment]
Hi,

Azure DevOps Pipelines are available now and free to use for open source projects. I think it is worth to give it a try.
What do you think?

Greetings,
KirK

**Comment by loic-sharma** [comment]
@kirkone Yup, I'm working on this. See: https://sharml.visualstudio.com/BaGet

**Comment by kirkone** [comment]
@loic-sharma if I can provide any help please let me know.
maybe .yaml files are a good option for the builds.

**Comment by loic-sharma** [comment]
I’ve created an Azure Pipelines YAML file here: https://github.com/loic-sharma/BaGet/blob/master/.azure/pipelines/ci-official.yml

Please let me know if you have any suggestions. I’ll add GitHub release mechanisms in the future.
