### ISSUE TITLE
docker image dont run in 5000 run in 80

### ISSUE THREAD

**Issue by behroozbc** [loic-sharma/BaGet#563]
### Describe the bug
hi 
i want install baget form docker and see in document port 5000 but baget run in port 80 

![image](https://user-images.githubusercontent.com/20381616/88279563-89db6000-ccf9-11ea-859a-5488daacef16.png)

**Comment by ashishbhatia22** [comment]
We should modify the docker file and expose port 5000. Currently, only port 80 is exposed

**Comment by behroozbc** [comment]
@ashishbhatia22
Hi
Don't think when I check logs I see baget run on port 80 and don't run in 5000
In asp. Net core port 5000 for test and development

**Comment by abakumov-v** [comment]
Hello! Same issue. May be just change BaGet docs at this page https://loic-sharma.github.io/BaGet/installation/docker/ ?

**Comment by loic-sharma** [comment]
Thank you for reporting this! @behroozbc fixed this in https://github.com/loic-sharma/BaGet/pull/564
