### ISSUE TITLE
Add Continuous Delivery

### ISSUE THREAD

**Issue by Baklap4** [loic-sharma/BaGet#57]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Currently there's no continuous delivery. In other words this means we have to manually deploy our build outputs produced in #56. We don't want to do manual stuff as we're programmers so why not automate it? 

### Blocked by
* Blocked by #56 

### Expectations
The CD should be able to do:
- [ ] Deploy build outputs
    - [ ] Windows
    - [ ] Linux
    - [ ] OSx
- [ ] Create a new tag on GitHub
- [ ] Run nightly deploy

This will gives us a place to download artifacts from per version and a place to download the nightly build from.

**Comment by smazurov** [comment]
I think for this, publishing a docker image (under latest/nightly tags) would satisfy the requirements.

**Comment by tomzo** [comment]
I have implemented a pipeline which runs all tests and publishes in docker image only when all have passed. You can see it working in [my fork](https://github.com/ai-traders/baget).
Most of work for it is in PR #108

**Comment by loic-sharma** [comment]
I'd like to follow NuGet Package Explorer's setup:

1. Use [Nerdbank.GitVersioning](https://github.com/aarnott/Nerdbank.GitVersioning) to generate a version
2. Publish BaGet as Azure DevOps artifacts
3. With human approval, use [github-tools-vsts](https://github.com/marceloavf/github-tools-vsts)'s `Create or Modify GitHub Release` task to release the artifacts to GitHub
4. With human approval, publish a Docker image

**Comment by loic-sharma** [comment]
I've added Continuous Delivery to BaGet. You can:

* Download BaGet as a GitHub release: https://github.com/loic-sharma/BaGet/releases
* Install BaGet's components using NuGet: [`BaGet.Core`](https://www.nuget.org/packages/BaGet.Core) and [`BaGet.Azure`](https://www.nuget.org/packages/BaGet.Azure/0.1.1-prerelease)

I'll add support for Docker images in the future.

**Comment by BlythMeister** [comment]
![](https://media.giphy.com/media/5GoVLqeAOo6PK/200.gif)

**Comment by loic-sharma** [comment]
Closing this issue as BaGet has continuous delivery. Please let me know if you have any other suggestions!
