### ISSUE TITLE
[UI] Improve the "Used by" / "Dependents" look

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#570]
### Is your feature request related to a problem? Please describe.
The current UI for the "Dependents" feature is quite basic:

![image](https://user-images.githubusercontent.com/737941/89133592-f6144b80-d4d1-11ea-979a-b7649754cdde.png)

### Describe the solution you'd like
The UI should be improved to look like nuget.org's:

![image](https://user-images.githubusercontent.com/737941/89133597-09271b80-d4d2-11ea-93f0-e0b488270e92.png)

**Comment by davidackroyd99** [comment]
I can do this, please could you assign me the issue?

**Comment by loic-sharma** [comment]
Done! By the way, you will likely need to update the APIP to return more information. Here are some helpful links:

1. [`ISearchService.FindDependentsAsync`](https://github.com/loic-sharma/BaGet/blob/7c514bfe57a59b7ed086e37b73d61a8194306a20/src/BaGet.Core/Search/ISearchService.cs#L53-L55). This is the interface in the backend that finds the packages that depend on a given package.
1. [`Dependents.tsx`](https://github.com/loic-sharma/BaGet/blob/master/src/BaGet.UI/src/DisplayPackage/Dependents.tsx) - This is the React component that displays the dependents information.
