### ISSUE TITLE
 Where is the source code of libe_sqlite3.so ?

### ISSUE THREAD

**Issue by sunny868** [loic-sharma/BaGet#579]
There is libe_sqlite3.so just for arm、arm64、x64 and so on but not for mips64,so I want to rebuild it for mips64 arch . so can you tell me the  source code location of libe_sqlite3.so ? Thank you very much.

**Comment by loic-sharma** [comment]
I'm not sure. BaGet uses the Entity Framework Core's SQLite implementation:

https://github.com/loic-sharma/BaGet/blob/f0ee2c57c221fd6f0e866f051eb5892e464b85f0/src/BaGet.Database.Sqlite/BaGet.Database.Sqlite.csproj#L11

EF Core docs: https://docs.microsoft.com/en-us/ef/core/providers/sqlite/?tabs=dotnet-core-cli

I'd consider asking the EF Core folks. Alternatively, maybe the other EF Core providers like PostgreSQL or MySQL support mips64?

> I want to rebuild it for mips64 arch 

May I ask, why do you want to run BaGet on mips 64?

**Comment by sunny868** [comment]
Now,Our team has supported NETCORE on MIPS64 architecture,https://github.com/gsvm/coreclr 
so I want run BaGet on MIPS64 Arch.

**Comment by sunny868** [comment]
Thanks ,The source code of libe_sqlite3.so is https://github.com/ericsink/cb

**Comment by loic-sharma** [comment]
I'm glad you were able to find it! Please let me know if you run into any other issues or have additional questions.
