### ISSUE TITLE
Not able to upload a new version to the baget server

### ISSUE THREAD

**Issue by abidkhan4357** [loic-sharma/BaGet#584]
Bug Description:
I am not able to upload and push my nuget package new version to the server. I keep getting a  500 internal server error.  I am usign baget version v3 and when I push it using command below for some reason its always showing v2..

dotnet nuget push -s https://baget.dev-company.com/v3/index.json MyNuget.1.0.14.nupkg -k APIKey 

I get the following logs in cmd

Pushing MyNuget.1.0.14.nupkg to 'https://baget.dev-company.com/api/v2/package'...
  PUT https://baget.dev-company.com/api/v2/package
  InternalServerError https://baget.dev-company.com/api/v2/packagee/ 935ms
  PUT https://baget.dev-company.com/api/v2/package
  InternalServerError https://baget.dev-company.com/api/v2/package/ 360ms
  PUT https://baget.dev-company.com/api/v2/package
  InternalServerError https://baget.dev-company.com/api/v2/package/ 507ms
error: Response status code does not indicate success: 500 (Internal Server Error).

#Container Logs
fail: BaGet.Hosting.PackagePublishController[0]
      Exception thrown during package upload
System.InvalidOperationException: Failed to store package mynuget 1.0.14 due to conflict
   at BaGet.Core.PackageStorageService.SavePackageContentAsync(Package package, Stream packageStream, Stream nuspecStream, Stream readmeStream, Stream iconStream, CancellationToken cancellationToken) in /src/BaGet.Core/Storage/PackageStorageService.cs:line 141
   at BaGet.Core.PackageIndexingService.IndexAsync(Stream packageStream, CancellationToken cancellationToken) in /src/BaGet.Core/Indexing/PackageIndexingService.cs:line 163
   at BaGet.Hosting.PackagePublishController.Upload(CancellationToken cancellationToken) in /src/BaGet.Hosting/Controllers/PackagePublishController.cs:line 81

### To Reproduce
1. Using this version of BaGet v3
2. Do to your directory where your nuget package is and use this commnd to push to your server
dotnet nuget push -s https://baget.dev-company.com/v3/index.json MyNuget.1.0.14.nupkg -k APIKey 

### Expected behavior
Nuget package successfully uploaded to baget server

**Comment by loic-sharma** [comment]
Were you able to fix your issue? In case any one else runs into this problems, I would suggest [enabling hard deletions](https://loic-sharma.github.io/BaGet/configuration/#enable-package-hard-deletions), running [`dotnet nuget delete`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-delete) on the affected package, and then pushing it again.

**Comment by humhei** [comment]
I just fixed this by adding write permission of baget folder to iis user
![image](https://user-images.githubusercontent.com/25994449/188515048-f5365e2c-3cc4-4b0b-b7b0-12d3b4dccb6f.png)

Check https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-6.0#application-pool-identity for detail

**Comment by abidkhan4357** [comment]
Bro you respond after 2 years.. lmao
