### ISSUE TITLE
Controlling user access

### ISSUE THREAD

**Issue by tomko80** [loic-sharma/BaGet#592]
### Describe the bug
Tried to find in the documentation information about how user access can controlled within the system. Nothing found.

### To Reproduce
1. Go to https://loic-sharma.github.io/BaGet/
2. Searched for permissions, group, access...

### Expected behavior
Statement saying user access can be restricted or that this is not supported.

**Comment by patriksvensson** [comment]
@tomko80 There is some information here: https://loic-sharma.github.io/BaGet/configuration/#private-feeds

**Comment by tomko80** [comment]
Ah "private feeds", the only term I did not try :) Having this in BaGet could probably beat many of the commercial products.
