### ISSUE TITLE
baget behind nginx reverse proxy does not work properly

### ISSUE THREAD

**Issue by Banzai292** [loic-sharma/BaGet#603]
First: Please excuse my bad english!
I don't know if the behavior is a Nginx or Baget problem, but a full search didn't come up with the solution.
I know just enough about nginx and docker to run and access my containers on a server, but nothing more!
My guess is that determining and setting the url in the baget container is not complete.

### Describe the bug
Getting index with https://mydomain.com:4335/v3/index.json works. Provided links does not.
### To Reproduce
_baget.env_ like on documentation site [here](https://loic-sharma.github.io/BaGet/installation/docker/)
1. start docker container with: `sudo docker run -d --rm --name nuget-server -p 4334:80 --env-file baget.env -v "$(pwd)/baget-data:/var/baget" loicsharma/baget:latest`
2. configure nginx:
```
    server {
    listen 4335 ssl default_server;
    listen [::]:4335 ssl default_server;

    include snippets/mycertificatecom.conf;

    server_name mydomain.com;

    access_log /var/log/nginx/baget.access.log;
    error_log /var/log/nginx/baget.error.log;

    location / {
         proxy_pass http://localhost:4334/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         client_max_body_size 20M;
    }
    }
```
3. Open port 4335 in firewall
4. In browser goto: https://mydomain.com:4335 -> see package site
5. click 'Upload' and click link at 

> You can push packages using the service index https://mydomain.com:4335/v3/index.json

See screenshot image

6. Click any of the @id: lines fails, because url is not complete (missing port)
7. Expand url with port 4335 manually, everything ok

### Expected behavior
Resulting json from https://mydomain.com:4335/v3/index.json should contain the port 4335

### Screenshots
![grafik](https://user-images.githubusercontent.com/1905750/98667858-4c095280-234f-11eb-8eae-72e25352f415.png)

### Additional context
I have several docker container (eg. gitlab, postgresql, docker-registry, etc.) running on that server, with reverse-proxy settings.

Thanks in advance for any hint or suggestion, what goes wrong here.

**Comment by joeangry** [comment]
$host does not include the port number. If you use $http_host it should work as expected.

**Comment by Banzai292** [comment]
> Like this `proxy_set_header Host $http_host;`

Perfect! Seems to work as expected,  thank you!
