### ISSUE TITLE
Add the framework search option for Net5.

### ISSUE THREAD

**Issue by SeppPenner** [loic-sharma/BaGet#605]
### Is your feature request related to a problem? Please describe.
No problem.

### Describe the solution you'd like
Seeing the new Net5 in the framework search dropdown.

### Describe alternatives you've considered
None.

### Additional context
I have added this and will provide a pull request soon. However, how do you want to handle the OS specific stuff? https://docs.microsoft.com/en-us/dotnet/standard/frameworks#net-5-os-specific-tfms @loic-sharma

**Comment by loic-sharma** [comment]
> how do you want to handle the OS specific stuff?

Excellent question. I'm not sure yet, I've created a separate issue to track this problem: https://github.com/loic-sharma/BaGet/issues/607. Let's not block on supporting .NET 5 though :)
