### ISSUE TITLE
UI - Selecting an older package revision returns content for latest revision of a build.

### ISSUE THREAD

**Issue by hannesbarbez** [loic-sharma/BaGet#627]
### Describe the bug

On the UI, navigating to an older revision of a package returns the contents pertaining to the latest revision of the correct build number.

Selecting an older revision of a package, the route in the browser changes to the correct path, i.e. to the path of the selected package version (incl. correct revision number). However, the information (and download link) shown in the UI are on the topic of the latest revision, not the selected revision. 

### To Reproduce
A practical example using AWSSDK.Core:

Selecting version 3.5.1.**59** in the UI correctly navigates to /packages/awssdk.core/3.5.1.**59**, however the contents of the page shows the .NET CLI command for version 3.5.1.**60**:

![Revision bug](https://barbez.eu/wp-content/uploads/2021/02/image-1.png)

Clicking the "Download package" link on the /packages/awssdk.core/3.5.1.**59** page triggers the download of version 3.5.1.**60**, which is the latest revision of version 3.5.1.x, but should be downloading 3.5.1.**59**.

Likewise, clicking package 3.5.2.1 correctly navigates the browser to /packages/awssdk.core/3.5.2.1, however the page's information refers to version 3.5.2.10, which is the latest revision of 3.5.2.x.

### Expected behavior
Navigating to a version with a given revision number returns the information for the requested revised version, not the latest revision of that particular build.

### More information
The bug only applies to packages using a Major.Minor.Build.**Revision** versioning format.

BaGet runs in a container based on the image tagged 0b46f0ec87216e1dc6839277712ee07c1c2b611a from https://hub.docker.com/r/loicsharma/baget/tags?page=1&ordering=last_updated.

![Container and Image](https://barbez.eu/wp-content/uploads/2021/02/image-2.png)

I've started the container using the following parameters:
![Docker run](https://barbez.eu/wp-content/uploads/2021/02/image-3.png)

The bug can be reproduced both using a CentOS as well as Alpine Linux host machine for Docker.

**Comment by hannesbarbez** [comment]
@loic-sharma Would it make sense that I try to have a look into this issue? If so, where to start? By the way, thank you for this very nice piece of software :)

**Comment by loic-sharma** [comment]
Thanks for the excellent bug report! I apologize for the delay. This was a bug in BaGet's old React frontend due to inconsistencies between .NET and Javascript version parsing. This is fixed now that BaGet has moved to Razor Pages. I'll close this off for now, but let me know if you run into any additional problems!
