### ISSUE TITLE
Publish version as docker tags

### ISSUE THREAD

**Issue by viceice** [loic-sharma/BaGet#633]
### Is your feature request related to a problem? Please describe.
I like to have [renovate](/renovatebot/renovate) to be able to suggest updates with release notes.
Renovate is able to match the docker tag to a github release / git tag.

### Describe the solution you'd like
Please publish the corresponding github releases as docker tag and add the `org.opencontainers.image.source="https://github.com/loic-sharma/BaGet"` label to the image.

### Describe alternatives you've considered
No alternate 😕 

### Additional context
That way we can use a specific docker tag to reference and let renovate suggest updates to newer versions Instead of relying on latest digest and manually find the changes happened.

**Comment by loic-sharma** [comment]
Excellent suggestion! Versions will be tagged starting from 0.4.0-preview1 and on! 😎
