### ISSUE TITLE
Need better installation instruction

### ISSUE THREAD

**Issue by dtsob75** [loic-sharma/BaGet#652]
I am trying to install this, but the installation instructions are very lacking.  For example, on the IIS install, it says "copy the baget folder to the webserver."  Does this mean the entire baget set of folders or just the baget project folder?  No mention of compiling the solution, but i assume that is required.

Just really need a full cookbook on installing and setting up the tool.  It really sound inviting, but without more information, it is hard to proceed.

**Comment by yekanchi** [comment]
> I am trying to install this, but the installation instructions are very lacking. For example, on the IIS install, it says "copy the baget folder to the webserver." Does this mean the entire baget set of folders or just the baget project folder? No mention of compiling the solution, but i assume that is required.
> 
> Just really need a full cookbook on installing and setting up the tool. It really sound inviting, but without more information, it is hard to proceed.

compilation is not required. if you are familiar with asp.net core hosting  the release folder is sufficient.

**Comment by dtsob75** [comment]
Thanks for the reply, but I am still confused.  I followed the instructions for running it locally and I get the following error when I try to run the website (http://localhost:5000/)

 



 

I could figure out how to switch to dev environment.  I copied the BaGet folder to our uat server and when I try to run the website, I get:

 



 

As you can tell, I am not very versed in using asp.net core.  Any help you can give would be greatly appreciated.

 

 

 

Thanks,

 

Joel Zinn

Broken Arrow, OK
