### ISSUE TITLE
NPM Error when running in Docker via Docker Compose

### ISSUE THREAD

**Issue by matthew-rsi** [loic-sharma/BaGet#673]
### Describe the bug
I'm attempting to run BaGet Dockerized via Docker Compose. The use case is running / debugging multiple microservices locally and sharing a "local" NuGet feed amongst the containers. I initially followed the instructions to run BaGet via Docker and had it running. Then I started experimenting with getting it working via Docker Compose. I also reinstalled Node/NPM locally (not in a container) and updated it to the latest stable build. I even manually built BaGet via Dockerfile (rather than using the latest image) and it reinitialize NPM in WSL2 and no dice.

### To Reproduce
1. Using either the latest image of BaGet or the latest code
2. Run via Docker Compose
3. Go to localhost:5555
4. An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:.

[1] Ensure that 'npm' is installed and can be found in one of the PATH directories.
Current PATH enviroment variable is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Make sure the executable is in one of those directories, or update your PATH.

[2] See the InnerException for further details of the cause.))
System.Threading.Tasks.Task<TResult>.GetResultCore(bool waitCompletionNotification)

InvalidOperationException: Failed to start 'npm'. To resolve this:.

[1] Ensure that 'npm' is installed and can be found in one of the PATH directories.
Current PATH enviroment variable is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Make sure the executable is in one of those directories, or update your PATH.

[2] See the InnerException for further details of the cause.
Microsoft.AspNetCore.NodeServices.Npm.NpmScriptRunner.LaunchNodeProcess(ProcessStartInfo startInfo)

### Expected behavior
I would very much like to run BaGet Dockerized as a shared service that can be composed and reused amongst multiple Web API microservices. For some devs, using an internal, GitHub package feed will be fine. However, when working locally on internal, private packages, it would be incredibly useful to run off of a local server rather than the file system.

### Additional context
Docker Compose:

version: "3.9"
volumes:
  baget-data:
    external: true

services:
  baget:
    #image: loicsharma/baget:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baget
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApiKey=MY_KEY_GOES_HERE
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/baget.db
      - Search__Type=Database
    ports:
      - "5555:80"
    volumes:
      - baget-data:/var/baget

**Comment by matthew-rsi** [comment]
ASPNETCORE_ENVIRONMENT needs to be Production, not Development. Leaving this open, for now, as I'm still experimenting using this container to serve multiple other microservices running in their own containers.

**Comment by loic-sharma** [comment]
Hi, BaGet no longer uses NPM so this bug should no longer happen. I'll close this off for now but feel free to comment or create a new issue if anything else comes up!
