### ISSUE TITLE
Tagging releases as latest

### ISSUE THREAD

**Issue by xacobecm** [loic-sharma/BaGet#684]
### Is your feature request related to a problem? Please describe.
I am trying to make an Ansible role to deploy and configure BaGet. In order to do this properly, I'm making this API call to Github so the script can always get the latest version available: https://docs.github.com/en/rest/reference/repos#get-the-latest-release
However it looks like there is no release tagged as _latest_.

### Describe the solution you'd like
Tagging the new releases as _latest_. This would make easy for everyone to write scripts to update their BaGet instances with the latest code.

**Comment by loic-sharma** [comment]
Could you try again? You should be able to grab a latest release now.

FYI the current latest GitHub release isn't actually latest release as I messed it up. I'll do a new GitHub release soon once I merge this: https://github.com/loic-sharma/BaGet/pull/687. Sorry for the mess! Future releases should be a bit smoother 😅
