### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#7]
Today, the project is as simple as possible to enable fast iteration. Tests should be added once things stabilize.

**Comment by WernerMairl** [comment]
Hi
I like the idea of this project!
I have started to play with this Issue in my own fork....
here first step:

https://github.com/WernerMairl/BaGet/commit/e5ed8cab908f981c9a837eb2d5e268934534aad9

please advice
- if PR's are welcome
- Rules/Guidelines to follow (my commit comment contains a few comments about my rule/guideline selection

regards
Werner

**Comment by loic-sharma** [comment]
Replacing this with https://github.com/loic-sharma/BaGet/issues/480
