### ISSUE TITLE
Run alongside another AspNetCore application instead of a separate application

### ISSUE THREAD

**Issue by Dunge** [loic-sharma/BaGet#701]
I wish to have both a nuget server and my own web application running the same port 80/443.

IIS is usually used to be able to configure multiple applications on the same web server, but in my case my website use a feature (gRPC) IIS does not support in Windows Server 2019, so I have to switch to Kestrel web server instead, which only runs one application at once.

Would it be possible to have BaGet as a service (nuget library) instead of a separate executable so that it could live alongside another application in the same Kestrel server? I'm thinking of a service registered in the ServiceCollection DI container like:

    services.AddBaGet(options => { options.Path = "/BaGet" });

**Comment by Dunge** [comment]
Forget this, I believe using a reverse proxy to redirect to the proper application to be a better solution.

**Comment by loic-sharma** [comment]
Yup this is possible. Here are some examples:

* Simple - https://github.com/loic-sharma/BaGet/tree/main/samples/BaGetWebApplication
* More complicated - https://github.com/microsofthackathons/nuget-push/tree/main/src/NuGetServer

**Comment by Dunge** [comment]
Thanks. I personally won't so it, as I said before it's ridiculous trying to bundle lots of applications in one big project, I rather use a reverse proxy and keep separate web servers. But I do appreciate you taking the time to reply, and that sample seems quite clear and easy.
