### ISSUE TITLE
Split up the BaGet.Web project

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#73]
Right now, `BaGet.Web` is a netcoreapp2.1 project as it references `Microsoft.AspNetCore.App`. It should be split into two pieces:

1. Anything related to the serialization of NuGet's v3 protocol should be moved to a `BaGet.Protocol` project. This project should be netstandard2.0
2. The rest should be moved to the `BaGet` project.

**Comment by WernerMairl** [comment]
some additional information about ".AddApplicationPart", reason and history...
(we reference this issue in a comment inside a cs file)

https://github.com/aspnet/Mvc/issues/5992
https://stackoverflow.com/questions/43669633/why-is-testserver-not-able-to-find-controllers-when-controller-is-in-separate-as?noredirect=1#comment74386164_43669633

**Comment by loic-sharma** [comment]
This work is done.
