### ISSUE TITLE
 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by git102347501** [loic-sharma/BaGet#767]
I packed a package with a size of 1253kb
![1680242445774](https://user-images.githubusercontent.com/37917403/229035962-554cb494-0242-47c2-929e-828f654853a2.png)
An error was encountered while uploading
![1680242520966](https://user-images.githubusercontent.com/37917403/229036176-78085627-1daa-41f3-b324-de57f879054f.png)
When uploading relatively small packages, there is no ch problem with this issue

**My Env:
Centos7 + Nginx**

**Comment by Peymanpn** [comment]
You need to increase your nginx client body size
give it a bigger number than the default value, for example, 10 megabytes.

put it in `server` section:

```
client_max_body_size  10M;
```

**Comment by git102347501** [comment]
> You need to increase your nginx client body size give it a bigger number than the default value, for example, 10 megabytes.
> 
> put it in `server` section:
> 
> ```
> client_max_body_size  10M;
> ```

Thank you. After applying your settings, the problem has been resolved
