### ISSUE TITLE
Discussion about the new Options validation

### ISSUE THREAD

**Issue by WernerMairl** [loic-sharma/BaGet#77]
Hi
I'm talking about the following commit (specially OptionExtensions.cs)
https://github.com/loic-sharma/BaGet/commit/bda4d6f27eab86b09cc2b543961741b6c4c95fd2

I like the idea to bring all the validations in one Point (SPOT=Single Point of Truth)

Where i'm strugeling is the usage pattern - basically do you allow

``
DatabaseOption option = null;
option.EnsureValid();
``

I understand that your code  works - because implemented as Extension!

But it stops my flow during a code review because calling methods on null pointer is working ONLY for extensions and a normal code reader is not able to see ad hoc that the method is a extension method.

A few ideas how to solve that (overengineering included)

- implement validations as instance methods direct inside the class
    - bool IsValid()
    - bool IsValid(out Exception)
    - void EnsureValid() { if IsValid(out e)==false throw e}

the null check can/should remain on the caller side OR (new idea)
- rename the extension Method in something that says: this is a extension and a call with null is allowed)
- inside the extension method check for null, and then call EnsureValid on the instance....

just my 2 cent.....

**Comment by loic-sharma** [comment]
Can’t this problem be solved in extension methods by doing a `null` check on the inputted options? That seems like a simpler approach.

**Comment by WernerMairl** [comment]
>Why don’t you like validating options inside of the extension method directly

From the point of view of a code reader/reviewer:
My mind is focused to find code that is not working.
Doing a method call on a null pointer (or a not checked pointer) is a Red Flag.

Every Red Flag stops my flow and causes investigations because on a simple editor a i can't see/distinguish if the Method is a Instance Method or a Extension Method....

i have read big parts of aps.net, corefx and other codes => never used in this way....


>option classes as I feel that the options classes shouldn’t contain logic
first feeling: yes agree, because it is used only for serialization/deserialization

How many (real) checks (outside this null discussion) we have ?
most of the properties are strong typed => the deserializer inside IConfiguration does the checks....

**Comment by loic-sharma** [comment]
Most of ASP.NET Core’s methods for service collection, configuration, and dependency injection are actually extension methods on interfaces. This pattern works very well for them, and I think it’s perfectly fine once you become accustomed to it. I’ll check out your PR.

**Comment by loic-sharma** [comment]
Fixed in https://github.com/loic-sharma/BaGet/pull/147
