### ISSUE TITLE
I dont want use 5000port and localhost,How can i set the config?

### ISSUE THREAD

**Issue by boppluhvvnq96328** [loic-sharma/BaGet#772]
I dont want use 5000port and localhost,How can i set the config?
thank pro
dotnet baget.dll is cool with cmd.But it easy to shutdown by accident,can it run in background(like services?)

**Comment by boppluhvvnq96328** [comment]
/

**Comment by zou128865** [comment]
use IIS

**Comment by OndrejValenta** [comment]
And what is it you are running this on? Windows or Linux?

To the port change you can try to use this https://stackoverflow.com/a/66846488/5556714

**Comment by boppluhvvnq96328** [comment]
thank you^.^

**Comment by OndrejValenta** [comment]
> thank you^.^

👍
