### ISSUE TITLE
Delisting Packages doesn't remove them from UI

### ISSUE THREAD

**Issue by smazurov** [loic-sharma/BaGet#79]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Run `nuget delete <my package> <version> -Source BaGet` (version being "latest" version)
2. Refresh ui and check <my package> listing

### What did you expect to see?

1) Package version should not be the delisted version
2) On Package details versions on the right and the install command should not show delisted version

### What did you see instead?

The delisted version is not hidden.

### Output of `git rev-parse HEAD`: (_What version of BaGet are you using?_)

```
ff72d234ff5d3682ed8f350e7e072025fade1870
```

### What is your environment & configuration (arguments, platform, ...)?

Docker, linux

**Comment by loic-sharma** [comment]
Good catch!

**Comment by loic-sharma** [comment]
This should be fixed now. Feel free to open another issue if you find anything else! :)

**Comment by Adriien-M** [comment]
I don't know if it's the same issue, but when I delete a package I receive a successfull message from ther server. However it's not removed from the UI and even from the server, the folder is still present in the packages folder ... Currently, I use it in Kubernetes (docker) with SQLite and a volume for the BaGet data

**Comment by loic-sharma** [comment]
@Adriien-M What is your [`PackageDeletionBehavior`](https://loic-sharma.github.io/BaGet/configuration/#enabling-package-hard-deletions) configuration set to? The default is `Unlist` which hides the package instead of deleting it. You will need to update the value to `HardDelete` to delete the package.
