### ISSUE TITLE
Can BaGet server used with Only FileSystem , with out using database.

### ISSUE THREAD

**Issue by mubarak0443** [loic-sharma/BaGet#798]
Hi ,

New to Baget Server and exploring things here.

Can we use Baget with only FileSystem , without database. ?

Please help on this. ..

**Comment by mubarak0443** [comment]
@loic-sharma  please help on this

**Comment by pietrocarpinacci-dufercodev** [comment]
Hi, 
I don't think he will reply. This project isn't maintainer anymore from him. There is a project called [BaGetter](https://github.com/bagetter/BaGetter) that is a fork of Baget. You can try there.

Anyway I don't think you can use only filesystem without a database. The easiest way you can do is to configure Filesystem + SqlLite that is a filesystem database.
