### ISSUE TITLE
Update gitignore file to ignore .vscode folder

### ISSUE THREAD

**Issue by mishra14** [loic-sharma/BaGet#8]
Plus delete .vscode folder :)

**Comment by loic-sharma** [comment]
Thanks for the suggestion! The .vscode folder contains the default build/launch settings and may be useful for people that want to open the project in vscode and immediately run BaGet. I'll play around with setup experience with and without the folder and see what I should do :)

**Comment by loic-sharma** [comment]
Closing this as this is a common pattern used by numerous projects.
