### ISSUE TITLE
Notes about website/help

### ISSUE THREAD

**Issue by WernerMairl** [loic-sharma/BaGet#80]
Hi
not seen the website until now : nice ;-)

a) the Linkt o "Configurations Documentation" on 
https://loic-sharma.github.io/BaGet/#running-baget-on-docker
is not working (Page not found)

b) you are using a .env file in this example 
we should explain that all the "__" (double underscore) inside the env file are only encodings/transforms from env variable to Json

Storage__Type=FileSystem =>  

"Storage": {
    "Type": "FileSystem"
}

I saw a lot of questions about this on the Web - assuming that a lot of people is not aware about that....

**Comment by loic-sharma** [comment]
Thanks! I spent way too much time on it :)

a. Which link is broken? This link worked for me: https://loic-sharma.github.io/BaGet/#running-baget-on-docker
b. Sure! I can add a note about that

**Comment by loic-sharma** [comment]
I updated this page in b625a6b0e4c0d75756a9b53a3949b739e793bf77. Please let me know what you think! :)
