### ISSUE TITLE
Publish packages with visual studio

### ISSUE THREAD

**Issue by rong0312** [loic-sharma/BaGet#87]
Greetings!

I will keep it short and simple, 
I am trying to publish packages via VS wizard;

![screen shot 2018-08-30 at 17 01 51](https://user-images.githubusercontent.com/33253167/44856615-8a3a6000-ac76-11e8-8875-ade64b307d93.png)

as you can see, i opened a **shared location** (right into the packages volume -> into the container).
the nupkg file is successfuly pushed to the container's volume.

**The problem:** the wizard publishes the **nupkg** file only, and it doesn't seems to satisfy BaGet server - the package is not recognized.

i noticed that via the nuget CLI, when i push the nupkg file to BaGet some few other files and 
directories are generated - 

![screen shot 2018-08-30 at 17 08 50](https://user-images.githubusercontent.com/33253167/44856974-6b889900-ac77-11e8-93e8-3b21d1445660.png)

seems that this is the convention for BaGet package uploads. 

Any ideas how should i push package to my BaGet via VS, when VS published
a naked nupkg file only?

Thanks a lot!
Ron

**Comment by loic-sharma** [comment]
Hey there! You have to use the nuget or dotnet CLIs to push packages to BaGet. Visual Studio can only publish packages to [local NuGet feeds](https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds). BaGet isn't a local feed, so using this Visual Studio feature doesn't work with BaGet. Does that make sense?

**Comment by rong0312** [comment]
It does.
Currently I have a demand to replace the global NuGet repository for my company.
Programers do not like the CLI that much :)
I am considering to make a script, when ever a programer pushes package via VS, the script will be activated and will publish to BaGet via CLI.
I will update here regards this issue & solution, in case that i will obtain approval for that.

Thanks Sharma.

**Comment by loic-sharma** [comment]
Sounds good @rong0312, I'll go ahead and close this issue. Feel free to add updates here or in a new issue as they come up.

By the way, I recommend that you setup a build pipeline to download your code, build it, and then push the generated packages. Usually this build is kicked off automatically each time a change is committed to your source code. For more information, look into [continuous integration](https://en.wikipedia.org/wiki/Continuous_integration) and [continuous delivery](https://en.wikipedia.org/wiki/Continuous_delivery).
