### ISSUE TITLE
Request body too large

### ISSUE THREAD

**Issue by rong0312** [loic-sharma/BaGet#88]
Greetings,

After integration and testing, I found that certain package pushes got response code of 500,
and this is the reason: 

![screen shot 2018-09-03 at 14 19 26](https://user-images.githubusercontent.com/33253167/44984140-62077580-af84-11e8-9edf-d4d9ca47b4bc.png)

The packages that didn't make the push (and the size):

![screen shot 2018-09-03 at 14 23 33](https://user-images.githubusercontent.com/33253167/44984323-fc67b900-af84-11e8-89b6-cfb6b78d4f1c.png)

Seems that BaGet wont push packages over a given size.
Is this issue known? 
Is there any solution / possibility to increase the allowed post request?
This is the only issue that prevents our deployment on production.  

Thanks a lot, Ron

**Comment by rong0312** [comment]
UPDATE;

I solved this issue, I made a PR regards this solution.

**Comment by loic-sharma** [comment]
Fixed by https://github.com/loic-sharma/BaGet/commit/f3adb30bb2028673bfc78d960ad234c61e2d48dd
