### ISSUE TITLE
Container logs wont show.

### ISSUE THREAD

**Issue by rong0312** [loic-sharma/BaGet#92]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to view the BaGet logs with the command:
docker logs <baget container name> -f

### What did you expect to see?

ongoing logs of my operations. 

### What did you see instead?

![screen shot 2018-09-06 at 12 28 07](https://user-images.githubusercontent.com/33253167/45148760-adae5f00-b1d0-11e8-8507-187a56bcb8a4.png)

The goal was to test nuget.org caching, but that way i found that i cant see any logs.
Is this a known issue?
Cant find any useful information regards the WARN message.

Thank a lot.

**Comment by rong0312** [comment]
P.S
Not sure that this warn is concrete. 
There are no logs by definition?

**Comment by smazurov** [comment]
container logs just fine with debug/info level logging.

**Comment by rong0312** [comment]
Thank you @smazurov,
If you dont mind, can you explain how to achieve this log level?

**Comment by smazurov** [comment]
I set it in a appsettings.json  I think you can also achieve it with env vars but I don't have a concrete example, documentation might.

**Comment by loic-sharma** [comment]
@rong0312 You can update the logging level to `Debug` in two places:

1. In the `appsettings.json` file [here](https://github.com/loic-sharma/BaGet/blob/master/src/BaGet/appsettings.json#L32)
2. In Docker, By appending `Logging__LogLevel__Default=Debug` to the `baget.env` file
