### ISSUE TITLE
Make the package upload limit configurable

### ISSUE THREAD

**Issue by NN---** [loic-sharma/BaGet#95]
I wanted to use BaGet to host my C++ packages which are above 300MB.
The last commit limited package with 250MB.
Is there any goos reason for this if the package is hosted on my server

**Comment by loic-sharma** [comment]
This is the package size limit imposed by nuget.org, I would like to keep the behavior the same by default.

I'll make this configurable to unblock you. Sorry about that.

**Comment by loic-sharma** [comment]
I removed the upload limit from BaGet in 5d2220de2dad18719c1fa2e65ade73223fd23db6 as the upload limit can be enforced by IIS.
